const fs = require("fs");

function generateCards() {
  const cards = [];

  // Card 1 - ESPORTES RADICAIS (patoPoints: 2)
  cards.push({
    id: 1, theme: "ESPORTES RADICAIS", patoPoints: 2,
    questions: [
      { text: "Altura da maior rampa de skate do mundo (metros)", answer: 30 },
      { text: "Idade do surfista profissional mais velho", answer: 72 },
      { text: "Altura do salto mais alto de skydive (km)", answer: 39 },
      { text: "Recorde humano de apneia - segurar a respiracao debaixo d'agua (minutos)", answer: 24 },
      { text: "Velocidade recorde de um patinador no gelo (km/h)", answer: 103 },
      { text: "Peso maximo de um asa-delta padrao (kg)", answer: 150 },
      { text: "Numero de pessoas que ja saltaram do Monte Everest (base jump)", answer: 5 },
      { text: "Altura do maior bungee jump comercial do mundo (metros)", answer: 233 },
      { text: "Velocidade maxima de um wingsuit em voo (km/h)", answer: 290 },
      { text: "Numero de mortes no Monte Everest desde 1922", answer: 330 },
      { text: "Maior distancia percorrida em slackline (metros)", answer: 2710 },
      { text: "Tempo do mergulho livre mais longo com apneia (minutos)", answer: 11 },
      { text: "Altura da maior onda ja surfada (metros)", answer: 26 },
      { text: "Numero de voltas consecutivas de looping em montanha-russa (recorde)", answer: 14 },
      { text: "Idade minima para saltar de paraquedas no Brasil", answer: 16 },
      { text: "Numero de pessoas que ja foram ao espaco como turistas", answer: 60 },
      { text: "Velocidade maxima de uma moto de motocross (km/h)", answer: 160 },
      { text: "Numero de dias para escalar o Monte Everest (expedicao tipica)", answer: 60 },
      { text: "Altura do maior toboga de agua do mundo (metros)", answer: 51 },
      { text: "Recorde mundial de saltos de paraquedas em 24 horas", answer: 640 },
      { text: "Numero de pessoas que ja escalaram as 14 montanhas acima de 8000m", answer: 44 },
      { text: "Velocidade recorde de uma bicicleta em descida (km/h)", answer: 280 },
      { text: "Numero de acidentes fatais no Monte Everest em 2023", answer: 18 },
      { text: "Temperatura no topo do Everest no verao (Celsius negativos)", answer: 25 },
      { text: "Numero de pessoas que surfam a mesma onda em recorde mundial", answer: 110 },
      { text: "Comprimento do maior escorregador de agua do mundo (metros)", answer: 600 },
      { text: "Velocidade maxima de um snowboard em descida (km/h)", answer: 200 },
      { text: "Numero de metros de altura do maior rapel ja feito", answer: 1000 },
      { text: "Idade minima para pratica de bungee jump no Brasil", answer: 18 },
      { text: "Altura da ponte do maior bungee jump da America do Sul (metros)", answer: 106 },
    ],
  });

  // Card 2 - CORPO HUMANO (patoPoints: 3)
  cards.push({
    id: 2, theme: "CORPO HUMANO", patoPoints: 3,
    questions: [
      { text: "Comprimento medio do intestino delgado (metros)", answer: 7 },
      { text: "Ossos em uma mao", answer: 27 },
      { text: "Media de pelos em cada narina", answer: 120 },
      { text: "Media de peidos que uma pessoa da por dia", answer: 14 },
      { text: "Peso da pessoa mais pesada de todos os tempos (kg)", answer: 635 },
      { text: "Altura da pessoa mais alta que ja existiu (cm)", answer: 272 },
      { text: "Numero de musculos no corpo humano", answer: 650 },
      { text: "Litros de sangue bombeados pelo coracao por dia", answer: 7600 },
      { text: "Comprimento total de nervos no corpo humano (km)", answer: 75 },
      { text: "Numero de celulas no corpo humano (trilhoes)", answer: 37 },
      { text: "Numero de receptores olfativos no nariz humano (milhoes)", answer: 400 },
      { text: "Porcentagem do cerebro que e gordura", answer: 60 },
      { text: "Quantidade de saliva produzida por dia (litros)", answer: 2 },
      { text: "Tempo medio de piscada de olho (milissegundos)", answer: 150 },
      { text: "Numero de costelas em um ser humano adulto", answer: 24 },
      { text: "Comprimento total do sistema digestivo (metros)", answer: 9 },
      { text: "Numero de vertebras na coluna humana", answer: 33 },
      { text: "Frequencia cardiaca maxima teorica (batimentos por minuto)", answer: 220 },
      { text: "Numero de papilas gustativas na lingua (media)", answer: 10000 },
      { text: "Porcentagem do corpo que e agua em recem-nascidos", answer: 78 },
      { text: "Comprimento medio da traqueia humana (cm)", answer: 12 },
      { text: "Numero de lobos do cerebro humano", answer: 4 },
      { text: "Capacidade media da bexiga humana (ml)", answer: 500 },
      { text: "Numero de costelas falsas no corpo humano", answer: 4 },
      { text: "Diametro medio do globo ocular humano (mm)", answer: 24 },
      { text: "Numero de pares de nervos cranianos", answer: 12 },
      { text: "Unhas crescem quantos milimetros por mes em media", answer: 3 },
      { text: "Superficie total da pele humana (metros quadrados)", answer: 2 },
      { text: "Numero de dentes de leite em uma crianca", answer: 20 },
      { text: "Peso medio do figado humano adulto (kg)", answer: 1 },
    ],
  });

  // Card 3 - CARROS (patoPoints: 2)
  cards.push({
    id: 3, theme: "CARROS", patoPoints: 2,
    questions: [
      { text: "Comprimento da limusine mais longa do mundo (metros)", answer: 30 },
      { text: "Recorde de velocidade de um carro de Formula 1 (km/h)", answer: 378 },
      { text: "Numero de estados atravessados pela Rota 66", answer: 8 },
      { text: "Porcentagem de taxis no total de carros no mundo", answer: 1 },
      { text: "Recorde de pessoas dentro de um carro Smart", answer: 20 },
      { text: "Porcentagem de carros que sao pintados de branco", answer: 38 },
      { text: "Numero de carros produzidos no mundo por ano (milhoes)", answer: 70 },
      { text: "Velocidade recorde de um carro eletrico de producao (km/h)", answer: 412 },
      { text: "Numero medio de pecas em um automovel", answer: 30000 },
      { text: "Ano de lancamento do primeiro carro popular brasileiro (Fusca)", answer: 1959 },
      { text: "Numero de airbags no carro com mais airbags do mundo", answer: 12 },
      { text: "Preco do carro mais caro ja vendido (milhoes de dolares)", answer: 142 },
      { text: "Numero de marchas da maior caixa de cambio automatica", answer: 10 },
      { text: "Tempo do 0 a 100 km/h do carro de producao mais rapido (segundos)", answer: 2 },
      { text: "Numero de carros eletricos vendidos no mundo em 2024 (milhoes)", answer: 17 },
      { text: "Distancia maxima percorrida por um carro com um tanque (km)", answer: 2600 },
      { text: "Ano de fundacao da Ford", answer: 1903 },
      { text: "Numero de cilindros do motor do Bugatti Veyron", answer: 16 },
      { text: "Peso do carro de F1 com piloto (kg minimo)", answer: 798 },
      { text: "Capacidade do tanque de combustivel de um carro popular (litros)", answer: 50 },
      { text: "Numero de veiculos emplacados no Brasil em 2024 (milhoes)", answer: 2 },
      { text: "Velocidade maxima permitida em autobahns alemas (km/h)", answer: 130 },
      { text: "Numero de portas do primeiro Fusca", answer: 2 },
      { text: "Preco medio de um carro popular no Brasil (milhares de reais)", answer: 70 },
      { text: "Ano do primeiro carro hibrido de producao em massa (Prius)", answer: 1997 },
      { text: "Numero de cores basicas disponiveis para o Ford Modelo T", answer: 1 },
      { text: "Comprimento do menor carro de producao do mundo (cm)", answer: 134 },
      { text: "Litros de combustivel da maior categoria de caminhao (tanque)", answer: 1000 },
      { text: "Idade minima para dirigir no Brasil", answer: 18 },
      { text: "Potencia do carro de rua mais potente (CV)", answer: 1600 },
    ],
  });

  // Card 4 - ARQUITETURA (patoPoints: 3)
  cards.push({
    id: 4, theme: "ARQUITETURA", patoPoints: 3,
    questions: [
      { text: "Numero de andares no Burj Khalifa, o predio mais alto do mundo", answer: 163 },
      { text: "Numero de quartos em Versalhes (em centenas)", answer: 23 },
      { text: "Tamanho medio de um apartamento para alugar em Manhattan (m2)", answer: 65 },
      { text: "Altura do maior castelo de cartas ja construido (cm)", answer: 762 },
      { text: "Numero de degraus ate o topo da catedral de Notre Dame", answer: 387 },
      { text: "Numero de colunas no Partenon em Atenas", answer: 46 },
      { text: "Altura do edificio mais alto do Brasil (One Tower, metros)", answer: 290 },
      { text: "Numero de janelas no Burj Khalifa", answer: 24000 },
      { text: "Comprimento da Ponte Danyang-Kunshan na China (km)", answer: 164 },
      { text: "Numero de blocos de vidro na piramide do Louvre", answer: 673 },
      { text: "Anos para construir o Taj Mahal", answer: 22 },
      { text: "Numero de tuneis no edificio do Pentagono", answer: 28 },
      { text: "Inclinacao da Torre de Pisa em graus", answer: 4 },
      { text: "Numero de apartamentos no predio residencial mais alto do mundo", answer: 900 },
      { text: "Altura da cupula da Basilica de Sao Pedro (metros)", answer: 136 },
      { text: "Numero de ilhas artificiais no projeto The World (Dubai)", answer: 300 },
      { text: "Numero de banheiros na Casa Branca", answer: 35 },
      { text: "Altura da Torre Eiffel (metros)", answer: 330 },
      { text: "Numero de estatuas na Catedral de Notre Dame", answer: 28 },
      { text: "Andares do Empire State Building", answer: 102 },
      { text: "Numero de operarios que construiram o Taj Mahal (milhares)", answer: 20 },
      { text: "Numero de pontes em Amsterdam", answer: 1281 },
      { text: "Numero de degraus do Cristo Redentor", answer: 220 },
      { text: "Peso total da Estatua da Liberdade (toneladas)", answer: 225 },
      { text: "Numero de colunas no Templo de Zeus Olimpico", answer: 104 },
      { text: "Comprimento do Canal do Panama (km)", answer: 82 },
      { text: "Numero de telhas na Opera de Sydney (milhares)", answer: 1000 },
      { text: "Anos de construcao do Coliseu de Roma", answer: 8 },
      { text: "Numero de escadas rolantes no Burj Khalifa", answer: 8 },
      { text: "Numero de quartos no Palacio de Buckingham", answer: 775 },
    ],
  });

  // Card 5 - ANIMAIS (patoPoints: 2)
  cards.push({
    id: 5, theme: "ANIMAIS", patoPoints: 2,
    questions: [
      { text: "Anos de vida de uma tartaruga gigante de Galapagos", answer: 150 },
      { text: "Peso medio de um elefante africano (toneladas)", answer: 6 },
      { text: "Numero de patas de uma centopeia comum", answer: 30 },
      { text: "Velocidade maxima de um guepardo (km/h)", answer: 120 },
      { text: "Altura do salto de uma pulga (cm)", answer: 30 },
      { text: "Numero de especies conhecidas de aranhas", answer: 50000 },
      { text: "Numero de coracoes de um polvo", answer: 3 },
      { text: "Peso maximo de uma baleia azul (toneladas)", answer: 200 },
      { text: "Comprimento da lingua de um camaleao (cm)", answer: 60 },
      { text: "Dentes de um crocodilo ao longo da vida", answer: 3000 },
      { text: "Horas que um coalinha dorme por dia", answer: 20 },
      { text: "Gestacao de um elefante africano (meses)", answer: 22 },
      { text: "Numero de especies de passaros no mundo", answer: 10000 },
      { text: "Velocidade de voo de um falcao-peregrino em mergulho (km/h)", answer: 390 },
      { text: "Comprimento da maior cobra ja encontrada (metros)", answer: 10 },
      { text: "Numero de olhos de uma aranha saltadora", answer: 8 },
      { text: "Numero de bracos de uma estrela-do-mar", answer: 5 },
      { text: "Anos que um papagaio pode viver", answer: 80 },
      { text: "Velocidade de natacao de um pinguim (km/h)", answer: 36 },
      { text: "Peso do maior cavalo do mundo (kg)", answer: 1500 },
      { text: "Gestacao de uma baleia azul (meses)", answer: 12 },
      { text: "Numero de especies de primatas no mundo", answer: 500 },
      { text: "Comprimento do maior crocodilo ja registrado (metros)", answer: 6 },
      { text: "Velocidade maxima de um cavalo de corrida (km/h)", answer: 70 },
      { text: "Numero de tentaculos de uma agua-viva juba-de-leao", answer: 150 },
      { text: "Dentes de um tubarao-branco ao longo da vida", answer: 30000 },
      { text: "Numero de especies de repteis conhecidas", answer: 11000 },
      { text: "Anos que vive uma baleia-da-groenlandia", answer: 200 },
      { text: "Comprimento da maior ave do mundo (avestruz, metros)", answer: 2 },
      { text: "Numero de listras de uma zebra (media)", answer: 80 },
    ],
  });

  // Card 6 - ESPACO (patoPoints: 3)
  cards.push({
    id: 6, theme: "ESPACO", patoPoints: 3,
    questions: [
      { text: "Distancia da Terra a Lua (milhares de km)", answer: 384 },
      { text: "Numero de luas de Jupiter", answer: 95 },
      { text: "Temperatura na superficie do Sol (milhares de graus Celsius)", answer: 5500 },
      { text: "Anos que Plutao leva para orbitar o Sol", answer: 248 },
      { text: "Numero de satelites Starlink lancados ate 2025", answer: 7000 },
      { text: "Idade do universo (bilhoes de anos)", answer: 14 },
      { text: "Numero de pessoas que ja pisaram na Lua", answer: 12 },
      { text: "Diametro da Estacao Espacial Internacional (metros)", answer: 109 },
      { text: "Numero de estrelas na Via Lactea (bilhoes)", answer: 200 },
      { text: "Tempo que a luz do Sol leva ate a Terra (minutos)", answer: 8 },
      { text: "Numero de planetas conhecidos fora do sistema solar", answer: 5500 },
      { text: "Distancia de Marte a Terra na maior aproximacao (milhoes de km)", answer: 55 },
      { text: "Numero de missoes Apollo que pousaram na Lua", answer: 6 },
      { text: "Temperatura media em Marte (Celsius negativos)", answer: 63 },
      { text: "Numero de aneis de Saturno visiveis da Terra", answer: 7 },
      { text: "Diametro do maior asteroide do cinturao (Ceres, km)", answer: 940 },
      { text: "Numero de planetas no sistema solar", answer: 8 },
      { text: "Diametro do Sol (milhoes de km)", answer: 1 },
      { text: "Velocidade orbital da ISS (km/h)", answer: 28000 },
      { text: "Numero de luas de Saturno", answer: 146 },
      { text: "Temperatura na superficie de Venus (Celsius)", answer: 465 },
      { text: "Distancia de Netuno ao Sol (bilhoes de km)", answer: 4 },
      { text: "Diametro da Lua (km)", answer: 3474 },
      { text: "Idade do Sistema Solar (bilhoes de anos)", answer: 4 },
      { text: "Numero de astronautas que foram a lua no total", answer: 24 },
      { text: "Comprimento da Estacao Espacial Internacional (metros)", answer: 109 },
      { text: "Numero de dias para a Lua orbitar a Terra", answer: 27 },
      { text: "Numero de missoes Apollo no total", answer: 17 },
      { text: "Numero de estrelas visiveis a olho nu (milhares)", answer: 9 },
      { text: "Tempo para a luz viajar do Sol ate Plutao (horas)", answer: 5 },
    ],
  });

  // Card 7 - COMIDA (patoPoints: 2)
  cards.push({
    id: 7, theme: "COMIDA", patoPoints: 2,
    questions: [
      { text: "Calorias em um Big Mac", answer: 563 },
      { text: "Numero de pizzas vendidas por dia em Nova York", answer: 230000 },
      { text: "Comprimento do maior sanduiche ja feito (metros)", answer: 735 },
      { text: "Numero de variedades de batata no Peru", answer: 4000 },
      { text: "Preco do cafe mais caro do mundo por xicara (dolares)", answer: 75 },
      { text: "Peso da maior pizza do mundo (kg)", answer: 26000 },
      { text: "Numero de estrelas Michelin do restaurante com mais estrelas", answer: 5 },
      { text: "Peso do maior hamburguer ja feito (kg)", answer: 913 },
      { text: "Calorias em um rodizio de pizza (media por pessoa)", answer: 2500 },
      { text: "Numero de tipos de sushi existentes", answer: 100 },
      { text: "Anos de envelhecimento do queijo mais velho ja vendido", answer: 40 },
      { text: "Preco do prato mais caro do mundo (milhares de dolares)", answer: 25 },
      { text: "Numero medio de ingredientes em um prato de feijoada completa", answer: 20 },
      { text: "Temperatura ideal para fritar batatas (Celsius)", answer: 180 },
      { text: "Peso medio de uma barra de chocolate vendida no Brasil (gramas)", answer: 100 },
      { text: "Numero de refeicoes servidas pelo McDonald's por dia (milhoes)", answer: 69 },
      { text: "Calorias em uma fatia de pizza de mussarela media", answer: 285 },
      { text: "Numero de paises que tem McDonald's", answer: 120 },
      { text: "Temperatura de cozimento ideal para carne mal passada (Celsius)", answer: 55 },
      { text: "Gramas de acucar em uma lata de Coca-Cola", answer: 35 },
      { text: "Numero de estrelas Michelin maximas possiveis", answer: 3 },
      { text: "Milhoes de toneladas de arroz produzidas no Brasil por ano", answer: 10 },
      { text: "Calorias diarias recomendadas para um adulto medio", answer: 2000 },
      { text: "Numero de ovos usados na maior omelete do mundo", answer: 145000 },
      { text: "Peso do maior pao do mundo (kg)", answer: 1200 },
      { text: "Tempo de cozimento de um ovo cozido perfeito (minutos)", answer: 7 },
      { text: "Numero de restaurantes no Japao com estrela Michelin", answer: 400 },
      { text: "Preco medio de um prato feito no Brasil (reais)", answer: 25 },
      { text: "Anos de envelhecimento do vinagre balsamico tradicional", answer: 12 },
      { text: "Numero de ingredientes no guacamole tradicional", answer: 5 },
    ],
  });

  // Card 8 - DINOSSAUROS (patoPoints: 3)
  cards.push({
    id: 8, theme: "DINOSSAUROS", patoPoints: 3,
    questions: [
      { text: "Milhoes de anos desde a extincao dos dinossauros", answer: 65 },
      { text: "Comprimento do maior dinossauro ja descoberto (metros)", answer: 40 },
      { text: "Peso estimado de um T-Rex (toneladas)", answer: 8 },
      { text: "Numero de especies de dinossauros ja identificadas", answer: 700 },
      { text: "Velocidade maxima estimada de um Velociraptor (km/h)", answer: 64 },
      { text: "Comprimento dos dentes do T-Rex (cm)", answer: 30 },
      { text: "Milhoes de anos que os dinossauros dominaram a Terra", answer: 165 },
      { text: "Numero de chifres de um Triceratops", answer: 3 },
      { text: "Comprimento do pescoco de um Braquiossauro (metros)", answer: 9 },
      { text: "Peso do menor dinossauro ja encontrado (gramas)", answer: 110 },
      { text: "Numero de ovos encontrados no maior ninho fossilizado", answer: 30 },
      { text: "Comprimento da cauda de um Diplodoco (metros)", answer: 14 },
      { text: "Numero de dedos nas patas dianteiras do T-Rex", answer: 2 },
      { text: "Envergadura de asas de um Pterodactilo (metros)", answer: 10 },
      { text: "Milhoes de anos do periodo Triassico", answer: 50 },
      { text: "Numero de dinossauros no Parque dos Dinossauros (filme Jurassic Park)", answer: 15 },
      { text: "Altura do Braquiossauro (metros)", answer: 13 },
      { text: "Comprimento do Estegossauro (metros)", answer: 9 },
      { text: "Peso estimado do Argentinossauro (toneladas)", answer: 100 },
      { text: "Numero de placas osseas nas costas do Estegossauro", answer: 17 },
      { text: "Velocidade estimada do T-Rex (km/h)", answer: 27 },
      { text: "Comprimento do menor dinossauro conhecido (cm)", answer: 40 },
      { text: "Numero de especies de dinossauros voadores conhecidas", answer: 200 },
      { text: "Milhoes de anos do periodo Jurassico", answer: 56 },
      { text: "Comprimento das garras do Velociraptor (cm)", answer: 10 },
      { text: "Numero de dentes de um Triceratops", answer: 800 },
      { text: "Peso do cerebro do T-Rex (gramas)", answer: 400 },
      { text: "Milhoes de anos do periodo Cretaceo", answer: 80 },
      { text: "Comprimento do Espinossauro (metros)", answer: 15 },
      { text: "Numero de patas do T-Rex", answer: 2 },
    ],
  });

  // Card 9 - BRASIL (patoPoints: 2)
  cards.push({
    id: 9, theme: "BRASIL", patoPoints: 2,
    questions: [
      { text: "Populacao do Brasil em milhoes (2025)", answer: 216 },
      { text: "Numero de estados brasileiros", answer: 27 },
      { text: "Comprimento do rio Amazonas (km)", answer: 6992 },
      { text: "Numero de titulos mundiais de futebol do Brasil", answer: 5 },
      { text: "Porcentagem da Amazonia em territorio brasileiro", answer: 60 },
      { text: "Numero de idiomas indigenas ainda falados no Brasil", answer: 274 },
      { text: "Numero de regioes geograficas do Brasil", answer: 5 },
      { text: "Extensao territorial do Brasil (milhoes de km2)", answer: 8 },
      { text: "Numero de paises que fazem fronteira com o Brasil", answer: 10 },
      { text: "Populacao da cidade de Sao Paulo (milhoes)", answer: 12 },
      { text: "Ano da independencia do Brasil", answer: 1822 },
      { text: "Numero de vezes que o Brasil sediou a Copa do Mundo", answer: 2 },
      { text: "Numero de municipios no Brasil", answer: 5570 },
      { text: "Pico mais alto do Brasil (Pico da Neblina, metros)", answer: 2995 },
      { text: "Numero de presidentes que o Brasil ja teve", answer: 39 },
      { text: "Comprimento do litoral brasileiro (km)", answer: 7491 },
      { text: "Ano do descobrimento do Brasil", answer: 1500 },
      { text: "Numero de Copas do Mundo vencidas pelo Brasil no feminino", answer: 0 },
      { text: "Populacao do Rio de Janeiro (milhoes)", answer: 6 },
      { text: "Numero de deputados federais no Brasil", answer: 513 },
      { text: "Numero de senadores no Brasil", answer: 81 },
      { text: "Idade minima para votar no Brasil", answer: 16 },
      { text: "Anos da ditadura militar no Brasil", answer: 21 },
      { text: "Numero de ministerios no governo federal (2025)", answer: 37 },
      { text: "Idade minima para ser presidente do Brasil", answer: 35 },
      { text: "Numero de estados na regiao Nordeste", answer: 9 },
      { text: "Numero de estados na regiao Norte", answer: 7 },
      { text: "Fuso horario de Brasilia em relacao a GMT (horas atrasado)", answer: 3 },
      { text: "Numero de unidades federativas do Brasil", answer: 27 },
      { text: "Ano da Proclamacao da Republica", answer: 1889 },
    ],
  });

  // Card 10 - MUSICA (patoPoints: 3)
  cards.push({
    id: 10, theme: "MUSICA", patoPoints: 3,
    questions: [
      { text: "Numero de teclas em um piano padrao", answer: 88 },
      { text: "Numero de sinfonias compostas por Beethoven", answer: 9 },
      { text: "Duracao da musica mais longa ja gravada (horas)", answer: 639 },
      { text: "Numero de streams de 'Blinding Lights' (bilhoes)", answer: 4 },
      { text: "Ano do primeiro festival Woodstock", answer: 1969 },
      { text: "Numero de discos vendidos pelos Beatles (milhoes)", answer: 600 },
      { text: "Numero de cordas em um violao padrao", answer: 6 },
      { text: "Numero de categorias no Grammy Awards", answer: 94 },
      { text: "Idade de Mozart ao compor sua primeira sinfonia", answer: 8 },
      { text: "Numero de instrumentos em uma orquestra sinfonica completa", answer: 100 },
      { text: "Segundos de reconhecimento de uma musica pelo Shazam (milhoes de buscas por dia)", answer: 30 },
      { text: "Numero de albums vendidos por Michael Jackson 'Thriller' (milhoes)", answer: 70 },
      { text: "Batidas por minuto de uma musica techno tipica", answer: 140 },
      { text: "Numero de notas musicais na escala cromatica ocidental", answer: 12 },
      { text: "Numero de palcos do Rock in Rio (todos os dias)", answer: 5 },
      { text: "Ano de lancamento do primeiro disco de vinil comercial", answer: 1948 },
      { text: "Numero de sinfonias compostas por Mozart", answer: 41 },
      { text: "Idade de Beethoven ao ficar completamente surdo", answer: 44 },
      { text: "Numero de membros dos Beatles", answer: 4 },
      { text: "Duracao do Rock in Rio (dias)", answer: 7 },
      { text: "Numero de edicoes do Rock in Rio no Brasil", answer: 9 },
      { text: "Numero de cordas em um baixo eletrico padrao", answer: 4 },
      { text: "Ano de fundacao do Spotify", answer: 2006 },
      { text: "Numero de musicas no album 'The White Album' dos Beatles", answer: 30 },
      { text: "Batimentos por minuto de uma musica classica andante", answer: 80 },
      { text: "Numero de composicoes de Chopin", answer: 230 },
      { text: "Idade de Michael Jackson ao lancar seu primeiro album solo", answer: 21 },
      { text: "Numero de paises em que o Rock in Rio ja aconteceu", answer: 4 },
      { text: "Numero de valsas compostas por Strauss", answer: 150 },
      { text: "Numero de publico total do primeiro Rock in Rio (milhoes)", answer: 1 },
    ],
  });

  ADD_REMAINING_CARDS_HERE

  const output = "import { Card } from \"@/game-engine/types\";\n\nexport const cards: Card[] = " + JSON.stringify(cards, null, 2) + ";\n";

  fs.writeFileSync("./src/cards/data.ts", output, "utf8");
  console.log("File generated successfully.");
  console.log("Cards:", cards.length);
  cards.forEach(c => console.log(`  Card ${c.id}: ${c.questions.length} questions`));
}

generateCards();
