import { Card } from "@/game-engine/types";

export const cards: Card[] = [
  {
    id: 1, theme: "ESPORTES RADICAIS", patoPoints: 2,
    questions: [
      { text: "Altura da maior rampa de skate do mundo (metros)", answer: 30 },
      { text: "Idade do surfista profissional mais velho", answer: 72 },
      { text: "Altura do salto mais alto de skydive (km)", answer: 39 },
      { text: "Recorde humano de apneia - segurar a respiracao debaixo d'agua (minutos)", answer: 24 },
      { text: "Velocidade recorde de um patinador no gelo (km/h)", answer: 103 },
      { text: "Peso maximo de um asa-delta padrao (kg)", answer: 150 },
      { text: "Numero de pessoas que ja saltaram do Monte Everest (base jump)", answer: 5 },
      { text: "Altura do maior bungee jump comercial do mundo (metros)", answer: 233 },
      { text: "Velocidade maxima de um wingsuit em voo (km/h)", answer: 290 },
      { text: "Numero de mortes no Monte Everest desde 1922", answer: 330 },
      { text: "Maior distancia percorrida em slackline (metros)", answer: 2710 },
      { text: "Tempo do mergulho livre mais longo com apneia (minutos)", answer: 11 },
      { text: "Altura da maior onda ja surfada (metros)", answer: 26 },
      { text: "Numero de voltas consecutivas de looping em montanha-russa (recorde)", answer: 14 },
      { text: "Idade minima para saltar de paraquedas no Brasil", answer: 16 },
      { text: "Numero de pessoas que ja foram ao espaco como turistas", answer: 60 },
    ],
  },
  {
    id: 2, theme: "CORPO HUMANO", patoPoints: 3,
    questions: [
      { text: "Comprimento medio do intestino delgado (metros)", answer: 7 },
      { text: "Ossos em uma mao", answer: 27 },
      { text: "Media de pelos em cada narina", answer: 120 },
      { text: "Media de peidos que uma pessoa da por dia", answer: 14 },
      { text: "Peso da pessoa mais pesada de todos os tempos (kg)", answer: 635 },
      { text: "Altura da pessoa mais alta que ja existiu (cm)", answer: 272 },
      { text: "Numero de musculos no corpo humano", answer: 650 },
      { text: "Litros de sangue bombeados pelo coracao por dia", answer: 7600 },
      { text: "Comprimento total de nervos no corpo humano (km)", answer: 75 },
      { text: "Numero de celulas no corpo humano (trilhoes)", answer: 37 },
      { text: "Numero de receptores olfativos no nariz humano (milhoes)", answer: 400 },
      { text: "Porcentagem do cerebro que e gordura", answer: 60 },
      { text: "Quantidade de saliva produzida por dia (litros)", answer: 1.5 },
      { text: "Tempo medio de piscada de olho (milissegundos)", answer: 150 },
      { text: "Numero de costelas em um ser humano adulto", answer: 24 },
      { text: "Comprimento total do sistema digestivo (metros)", answer: 9 },
    ],
  },
  {
    id: 3, theme: "CARROS", patoPoints: 2,
    questions: [
      { text: "Comprimento da limusine mais longa do mundo (metros)", answer: 30 },
      { text: "Recorde de velocidade de um carro de Formula 1 (km/h)", answer: 378 },
      { text: "Numero de estados atravessados pela Rota 66", answer: 8 },
      { text: "Porcentagem de taxis no total de carros no mundo", answer: 1 },
      { text: "Recorde de pessoas dentro de um carro Smart", answer: 20 },
      { text: "Porcentagem de carros que sao pintados de branco", answer: 38 },
      { text: "Numero de carros produzidos no mundo por ano (milhoes)", answer: 70 },
      { text: "Velocidade recorde de um carro eletrico de producao (km/h)", answer: 412 },
      { text: "Numero medio de pecas em um automovel", answer: 30000 },
      { text: "Ano de lancamento do primeiro carro popular brasileiro (Fusca)", answer: 1959 },
      { text: "Numero de airbags no carro com mais airbags do mundo", answer: 12 },
      { text: "Preco do carro mais caro ja vendido (milhoes de dolares)", answer: 142 },
      { text: "Numero de marchas da maior caixa de cambio automatica", answer: 10 },
      { text: "Tempo do 0 a 100 km/h do carro de producao mais rapido (segundos)", answer: 1.8 },
      { text: "Numero de carros eletricos vendidos no mundo em 2024 (milhoes)", answer: 17 },
      { text: "Distancia maxima percorrida por um carro com um tanque (km)", answer: 2600 },
    ],
  },
  {
    id: 4, theme: "ARQUITETURA", patoPoints: 3,
    questions: [
      { text: "Numero de andares no Burj Khalifa, o predio mais alto do mundo", answer: 163 },
      { text: "Numero de quartos em Versalhes (em centenas)", answer: 23 },
      { text: "Tamanho medio de um apartamento para alugar em Manhattan (m2)", answer: 65 },
      { text: "Altura do maior castelo de cartas ja construido (cm)", answer: 762 },
      { text: "Numero de degraus ate o topo da catedral de Notre Dame", answer: 387 },
      { text: "Numero de colunas no Partenon em Atenas", answer: 46 },
      { text: "Altura do edificio mais alto do Brasil (One Tower, metros)", answer: 290 },
      { text: "Numero de janelas no Burj Khalifa", answer: 24000 },
      { text: "Comprimento da Ponte Danyang-Kunshan na China (km)", answer: 164 },
      { text: "Numero de blocos de vidro na piramide do Louvre", answer: 673 },
      { text: "Anos para construir o Taj Mahal", answer: 22 },
      { text: "Numero de tuneis no edificio do Pentagono", answer: 28 },
      { text: "Inclinacao da Torre de Pisa em graus", answer: 4 },
      { text: "Numero de apartamentos no predio residencial mais alto do mundo", answer: 900 },
      { text: "Altura da cupula da Basilica de Sao Pedro (metros)", answer: 136 },
      { text: "Numero de ilhas artificiais no projeto The World (Dubai)", answer: 300 },
    ],
  },
  {
    id: 5, theme: "ANIMAIS", patoPoints: 2,
    questions: [
      { text: "Anos de vida de uma tartaruga gigante de Galapagos", answer: 150 },
      { text: "Peso medio de um elefante africano (toneladas)", answer: 6 },
      { text: "Numero de patas de uma centopeia comum", answer: 30 },
      { text: "Velocidade maxima de um guepardo (km/h)", answer: 120 },
      { text: "Altura do salto de uma pulga (cm)", answer: 30 },
      { text: "Numero de especies conhecidas de aranhas", answer: 50000 },
      { text: "Numero de coracoes de um polvo", answer: 3 },
      { text: "Peso maximo de uma baleia azul (toneladas)", answer: 200 },
      { text: "Comprimento da lingua de um camaleao (cm)", answer: 60 },
      { text: "Dentes de um crocodilo ao longo da vida", answer: 3000 },
      { text: "Horas que um coalinha dorme por dia", answer: 20 },
      { text: "Gestacao de um elefante africano (meses)", answer: 22 },
      { text: "Numero de especies de passaros no mundo", answer: 10000 },
      { text: "Velocidade de voo de um falcao-peregrino em mergulho (km/h)", answer: 390 },
      { text: "Comprimento da maior cobra ja encontrada (metros)", answer: 10 },
      { text: "Numero de olhos de uma aranha saltadora", answer: 8 },
    ],
  },
  {
    id: 6, theme: "ESPACO", patoPoints: 3,
    questions: [
      { text: "Distancia da Terra a Lua (milhares de km)", answer: 384 },
      { text: "Numero de luas de Jupiter", answer: 95 },
      { text: "Temperatura na superficie do Sol (milhares de graus Celsius)", answer: 5500 },
      { text: "Anos que Plutao leva para orbitar o Sol", answer: 248 },
      { text: "Numero de satelites Starlink lancados ate 2025", answer: 7000 },
      { text: "Idade do universo (bilhoes de anos)", answer: 14 },
      { text: "Numero de pessoas que ja pisaram na Lua", answer: 12 },
      { text: "Diametro da Estacao Espacial Internacional (metros)", answer: 109 },
      { text: "Numero de estrelas na Via Lactea (bilhoes)", answer: 200 },
      { text: "Tempo que a luz do Sol leva ate a Terra (minutos)", answer: 8 },
      { text: "Numero de planetas conhecidos fora do sistema solar", answer: 5500 },
      { text: "Distancia de Marte a Terra na maior aproximacao (milhoes de km)", answer: 55 },
      { text: "Numero de missoes Apollo que pousaram na Lua", answer: 6 },
      { text: "Temperatura media em Marte (Celsius negativos)", answer: 63 },
      { text: "Numero de aneis de Saturno visiveis da Terra", answer: 7 },
      { text: "Diametro do maior asteroide do cinturao (Ceres, km)", answer: 940 },
    ],
  },
  {
    id: 7, theme: "COMIDA", patoPoints: 2,
    questions: [
      { text: "Calorias em um Big Mac", answer: 563 },
      { text: "Numero de pizzas vendidas por dia em Nova York", answer: 230000 },
      { text: "Comprimento do maior sanduiche ja feito (metros)", answer: 735 },
      { text: "Numero de variedades de batata no Peru", answer: 4000 },
      { text: "Preco do cafe mais caro do mundo por xicara (dolares)", answer: 75 },
      { text: "Peso da maior pizza do mundo (kg)", answer: 26000 },
      { text: "Numero de estrelas Michelin do restaurante com mais estrelas", answer: 5 },
      { text: "Peso do maior hamburguer ja feito (kg)", answer: 913 },
      { text: "Calorias em um rodizio de pizza (media por pessoa)", answer: 2500 },
      { text: "Numero de tipos de sushi existentes", answer: 100 },
      { text: "Anos de envelhecimento do queijo mais velho ja vendido", answer: 40 },
      { text: "Preco do prato mais caro do mundo (milhares de dolares)", answer: 25 },
      { text: "Numero medio de ingredientes em um prato de feijoada completa", answer: 20 },
      { text: "Temperatura ideal para fritar batatas (Celsius)", answer: 180 },
      { text: "Peso medio de uma barra de chocolate vendida no Brasil (gramas)", answer: 100 },
      { text: "Numero de refeicoes servidas pelo McDonald's por dia (milhoes)", answer: 69 },
    ],
  },
  {
    id: 8, theme: "DINOSSAUROS", patoPoints: 3,
    questions: [
      { text: "Milhoes de anos desde a extincao dos dinossauros", answer: 65 },
      { text: "Comprimento do maior dinossauro ja descoberto (metros)", answer: 40 },
      { text: "Peso estimado de um T-Rex (toneladas)", answer: 8 },
      { text: "Numero de especies de dinossauros ja identificadas", answer: 700 },
      { text: "Velocidade maxima estimada de um Velociraptor (km/h)", answer: 64 },
      { text: "Comprimento dos dentes do T-Rex (cm)", answer: 30 },
      { text: "Milhoes de anos que os dinossauros dominaram a Terra", answer: 165 },
      { text: "Numero de chifres de um Triceratops", answer: 3 },
      { text: "Comprimento do pescoco de um Braquiossauro (metros)", answer: 9 },
      { text: "Peso do menor dinossauro ja encontrado (gramas)", answer: 110 },
      { text: "Numero de ovos encontrados no maior ninho fossilizado", answer: 30 },
      { text: "Comprimento da cauda de um Diplodoco (metros)", answer: 14 },
      { text: "Numero de dedos nas patas dianteiras do T-Rex", answer: 2 },
      { text: "Envergadura de asas de um Pterodactilo (metros)", answer: 10 },
      { text: "Milhoes de anos do periodo Triassico", answer: 50 },
      { text: "Numero de dinossauros no Parque dos Dinossauros (filme Jurassic Park)", answer: 15 },
    ],
  },
  {
    id: 9, theme: "BRASIL", patoPoints: 2,
    questions: [
      { text: "Populacao do Brasil em milhoes (2025)", answer: 216 },
      { text: "Numero de estados brasileiros", answer: 26 },
      { text: "Comprimento do rio Amazonas (km)", answer: 6992 },
      { text: "Numero de titulos mundiais de futebol do Brasil", answer: 5 },
      { text: "Porcentagem da Amazonia em territorio brasileiro", answer: 60 },
      { text: "Numero de idiomas indigenas ainda falados no Brasil", answer: 274 },
      { text: "Numero de regioes geograficas do Brasil", answer: 5 },
      { text: "Extensao territorial do Brasil (milhoes de km2)", answer: 8.5 },
      { text: "Numero de paises que fazem fronteira com o Brasil", answer: 10 },
      { text: "Populacao da cidade de Sao Paulo (milhoes)", answer: 12 },
      { text: "Ano da independencia do Brasil", answer: 1822 },
      { text: "Numero de vezes que o Brasil sediou a Copa do Mundo", answer: 2 },
      { text: "Numero de municipios no Brasil", answer: 5570 },
      { text: "Pico mais alto do Brasil (Pico da Neblina, metros)", answer: 2995 },
      { text: "Numero de presidentes que o Brasil ja teve", answer: 39 },
      { text: "Comprimento do litoral brasileiro (km)", answer: 7491 },
    ],
  },
  {
    id: 10, theme: "MUSICA", patoPoints: 3,
    questions: [
      { text: "Numero de teclas em um piano padrao", answer: 88 },
      { text: "Numero de sinfonias compostas por Beethoven", answer: 9 },
      { text: "Duracao da musica mais longa ja gravada (horas)", answer: 639 },
      { text: "Numero de streams de 'Blinding Lights' (bilhoes)", answer: 4 },
      { text: "Ano do primeiro festival Woodstock", answer: 1969 },
      { text: "Numero de discos vendidos pelos Beatles (milhoes)", answer: 600 },
      { text: "Numero de cordas em um violao padrao", answer: 6 },
      { text: "Numero de categorias no Grammy Awards", answer: 94 },
      { text: "Idade de Mozart ao compor sua primeira sinfonia", answer: 8 },
      { text: "Numero de instrumentos em uma orquestra sinfonica completa", answer: 100 },
      { text: "Segundos de reconhecimento de uma musica pelo Shazam (milhoes de buscas por dia)", answer: 30 },
      { text: "Numero de albums vendidos por Michael Jackson 'Thriller' (milhoes)", answer: 70 },
      { text: "Batidas por minuto de uma musica techno tipica", answer: 140 },
      { text: "Numero de notas musicais na escala cromatica ocidental", answer: 12 },
      { text: "Numero de palcos do Rock in Rio (todos os dias)", answer: 5 },
      { text: "Ano de lancamento do primeiro disco de vinil comercial", answer: 1948 },
    ],
  },
  {
    id: 11, theme: "OCEANOS", patoPoints: 2,
    questions: [
      { text: "Profundidade da Fossa das Marianas (km)", answer: 11 },
      { text: "Porcentagem da superficie da Terra coberta por oceanos", answer: 71 },
      { text: "Numero de especies de tubaroes conhecidas", answer: 500 },
      { text: "Velocidade de natacao de um atum (km/h)", answer: 75 },
      { text: "Numero de coracoes de um polvo", answer: 3 },
      { text: "Peso maximo de uma baleia azul (toneladas)", answer: 200 },
      { text: "Numero de oceanos no planeta Terra", answer: 5 },
      { text: "Porcentagem dos oceanos ainda inexplorada", answer: 80 },
      { text: "Profundidade media dos oceanos (metros)", answer: 3700 },
      { text: "Numero de especies de peixes conhecidas no mundo", answer: 34000 },
      { text: "Volume total de agua nos oceanos (bilhoes de km3)", answer: 1.3 },
      { text: "Temperatura media da superficie dos oceanos (Celsius)", answer: 17 },
      { text: "Comprimento da Grande Barreira de Corais (km)", answer: 2300 },
      { text: "Numero de bracos de uma estrela-do-mar comum", answer: 5 },
      { text: "Anos de vida de uma baleia-da-Groenlandia", answer: 200 },
      { text: "Velocidade maxima de um barco a vela de competicao (km/h)", answer: 65 },
    ],
  },
  {
    id: 12, theme: "CINEMA", patoPoints: 2,
    questions: [
      { text: "Numero de filmes do MCU (ate 2025)", answer: 35 },
      { text: "Duracao do filme mais longo ja feito (horas)", answer: 87 },
      { text: "Orcamento de Avatar (2009) em milhoes de dolares", answer: 237 },
      { text: "Numero de Oscars ganhos por Walt Disney", answer: 26 },
      { text: "Preco do primeiro ingresso de cinema (centavos de dolar)", answer: 5 },
      { text: "Numero de tomadas para a cena da escada em O Poderoso Chefao", answer: 40 },
      { text: "Bilheteria total de Vingadores: Ultimato (bilhoes de dolares)", answer: 2.8 },
      { text: "Numero de filmes dirigidos por Steven Spielberg", answer: 34 },
      { text: "Idade do ator mais jovem a ganhar um Oscar", answer: 10 },
      { text: "Numero de categorias no Oscar (2025)", answer: 23 },
      { text: "Ano de lancamento do primeiro filme colorido", answer: 1939 },
      { text: "Numero de dubladores para a voz do Darth Vader", answer: 3 },
      { text: "Numero de filmes em que Samuel L. Jackson aparece", answer: 150 },
      { text: "Duracao do menor filme a ganhar um Oscar (minutos)", answer: 40 },
      { text: "Numero de extras usados na cena funebre de Gandhi", answer: 300000 },
      { text: "Orcamento do filme brasileiro mais caro (milhoes de reais)", answer: 60 },
    ],
  },
  {
    id: 13, theme: "EGITO ANTIGO", patoPoints: 3,
    questions: [
      { text: "Idade estimada das piramides de Gize (milhares de anos)", answer: 4.5 },
      { text: "Numero de blocos na Grande Piramide (milhoes)", answer: 2 },
      { text: "Peso medio de cada bloco da Grande Piramide (toneladas)", answer: 2.5 },
      { text: "Numero de dinastias do Egito Antigo", answer: 31 },
      { text: "Comprimento do rio Nilo (km)", answer: 6650 },
      { text: "Numero de deuses no panteao egipcio", answer: 2000 },
      { text: "Altura original da Grande Piramide (metros)", answer: 146 },
      { text: "Numero de anos do reinado de Ramsés II", answer: 66 },
      { text: "Peso da estatua da Esfinge de Gize (toneladas)", answer: 20000 },
      { text: "Numero de camaras conhecidas na Grande Piramide", answer: 3 },
      { text: "Idade de Tutancamon ao se tornar farao", answer: 9 },
      { text: "Numero de objetos no tumulo de Tutancamon", answer: 5000 },
      { text: "Anos que durou a construcao da Grande Piramide", answer: 20 },
      { text: "Numero de hieroglifos conhecidos", answer: 1000 },
      { text: "Comprimento do sarcófago de Tutancamon (metros)", answer: 2.7 },
      { text: "Numero de mastabas (tumulos) ao redor das piramides", answer: 100 },
    ],
  },
  {
    id: 14, theme: "INTERNET", patoPoints: 2,
    questions: [
      { text: "Numero de sites na internet (bilhoes, 2025)", answer: 2 },
      { text: "Usuarios ativos do Facebook (bilhoes)", answer: 3 },
      { text: "Numero de emails enviados por dia (bilhoes)", answer: 347 },
      { text: "Tempo medio gasto por dia no celular (minutos)", answer: 235 },
      { text: "Porcentagem do trafego da internet que e de bots", answer: 42 },
      { text: "Ano de criacao do primeiro website", answer: 1991 },
      { text: "Numero de usuarios de internet no mundo (bilhoes)", answer: 5.3 },
      { text: "Numero de videos assistidos no YouTube por dia (bilhoes)", answer: 5 },
      { text: "Peso do primeiro servidor web (kg)", answer: 50 },
      { text: "Tempo medio de carregamento de uma pagina web (segundos)", answer: 2.5 },
      { text: "Numero de pesquisas no Google por dia (bilhoes)", answer: 8.5 },
      { text: "Porcentagem da internet que e a 'deep web'", answer: 90 },
      { text: "Ano de fundacao do Google", answer: 1998 },
      { text: "Porcentagem de brasileiros com acesso a internet", answer: 82 },
      { text: "Numero de dominios .com registrados (milhoes)", answer: 160 },
      { text: "Velocidade media da internet banda larga no Brasil (Mbps)", answer: 100 },
    ],
  },
  {
    id: 15, theme: "OLIMPIADAS", patoPoints: 3,
    questions: [
      { text: "Numero de paises participantes em Toquio 2020", answer: 206 },
      { text: "Recorde dos 100m rasos (segundos)", answer: 10 },
      { text: "Numero de medalhas de ouro de Michael Phelps", answer: 23 },
      { text: "Numero de esportes em Paris 2024", answer: 32 },
      { text: "Altura do salto com vara recorde (metros)", answer: 6 },
      { text: "Peso maximo levantado no halterofilismo olimpico (kg)", answer: 264 },
      { text: "Numero total de medalhas do Brasil na historia das Olimpiadas", answer: 150 },
      { text: "Ano da primeira Olimpiada da era moderna", answer: 1896 },
      { text: "Numero de aneis no simbolo olimpico", answer: 5 },
      { text: "Numero maximo de atletas por delegacao em uma Olimpiada", answer: 613 },
      { text: "Numero de paises que nunca ganharam uma medalha olimpica", answer: 70 },
      { text: "Recorde mundial da maratona (minutos)", answer: 120 },
      { text: "Numero de edicoes das Olimpiadas de Inverno", answer: 24 },
      { text: "Idade da atleta mais jovem a ganhar ouro olimpico", answer: 13 },
      { text: "Numero de esportes na primeira Olimpiada moderna (Atenas 1896)", answer: 9 },
      { text: "Numero de espectadores na cerimonia de abertura de Pequim 2008", answer: 91000 },
    ],
  },
  {
    id: 16, theme: "FUTEBOL", patoPoints: 2,
    questions: [
      { text: "Numero de gols de Pele na carreira", answer: 1283 },
      { text: "Capacidade do Maracana antes da reforma (milhares)", answer: 200 },
      { text: "Numero de Copas do Mundo disputadas ate 2022", answer: 22 },
      { text: "Recorde de gols em uma unica Copa (por um jogador)", answer: 13 },
      { text: "Numero de paises membros da FIFA", answer: 211 },
      { text: "Distancia percorrida por um jogador em media por jogo (km)", answer: 10 },
      { text: "Numero de gols de Cristiano Ronaldo na carreira (ate 2025)", answer: 900 },
      { text: "Numero de substituicoes permitidas por jogo atualmente", answer: 5 },
      { text: "Recorde de publico em um jogo de futebol (Maracana 1950)", answer: 199854 },
      { text: "Numero de titulos da Champions League do Real Madrid", answer: 15 },
      { text: "Duracao de uma partida de futebol (minutos)", answer: 90 },
      { text: "Numero de jogadores em campo por time", answer: 11 },
      { text: "Ano de fundacao da CBF", answer: 1914 },
      { text: "Numero de gols do maior artilheiro da historia das Copas (Klose)", answer: 16 },
      { text: "Tamanho oficial de um campo de futebol (comprimento maximo em metros)", answer: 120 },
      { text: "Numero de titulos brasileiros do Palmeiras (ate 2025)", answer: 12 },
    ],
  },
  {
    id: 17, theme: "VOLTA AO MUNDO", patoPoints: 2,
    questions: [
      { text: "Dias que Phileas Fogg levou na historia de Julio Verne", answer: 80 },
      { text: "Numero de fusos horarios no mundo", answer: 24 },
      { text: "Maior temperatura ja registrada na Terra (Celsius)", answer: 57 },
      { text: "Menor temperatura ja registrada na Terra (Celsius negativos)", answer: 89 },
      { text: "Numero de paises no mundo (2025)", answer: 195 },
      { text: "Circunferencia da Terra no Equador (km)", answer: 40075 },
      { text: "Recorde de volta ao mundo de aviao comercial (horas)", answer: 44 },
      { text: "Numero de continentes no mundo", answer: 6 },
      { text: "Numero de mares na Terra", answer: 7 },
      { text: "Porcentagem da populacao que vive no hemisferio norte", answer: 90 },
      { text: "Numero de pessoas que ja deram a volta ao mundo a pe", answer: 3 },
      { text: "Dias gastos na volta ao mundo de Fernao de Magalhaes", answer: 1082 },
      { text: "Numero de ilhas nas Filipinas", answer: 7641 },
      { text: "Maior altitude de uma cidade no mundo (La Rinconada, metros)", answer: 5100 },
      { text: "Distancia de uma volta ao mundo pela linha do Equador (km)", answer: 40075 },
      { text: "Numero de paises africanos", answer: 54 },
    ],
  },
  {
    id: 18, theme: "TECNOLOGIA", patoPoints: 3,
    questions: [
      { text: "Numero de transistores em um chip M2 Ultra (bilhoes)", answer: 134 },
      { text: "Ano de criacao do primeiro iPhone", answer: 2007 },
      { text: "Peso do primeiro computador ENIAC (toneladas)", answer: 27 },
      { text: "Numero de bits no primeiro processador Intel (4004)", answer: 4 },
      { text: "Velocidade da internet mais rapida ja registrada (Tbps)", answer: 319 },
      { text: "Porcentagem de usuarios mobile vs desktop no mundo", answer: 58 },
      { text: "Numero de linhas de codigo do Windows 10 (milhoes)", answer: 50 },
      { text: "Ano de criacao da World Wide Web", answer: 1989 },
      { text: "Numero de nucleos no processador com mais nucleos (servidor)", answer: 192 },
      { text: "Armazenamento do primeiro disquete (kilobytes)", answer: 80 },
      { text: "Numero de usuarios do ChatGPT nos primeiros dois meses (milhoes)", answer: 100 },
      { text: "Peso do primeiro disco rigido de 1GB (kg)", answer: 250 },
      { text: "Numero de patentes registradas por Thomas Edison", answer: 1093 },
      { text: "Ano do primeiro email enviado", answer: 1971 },
      { text: "Numero medio de notificacoes recebidas por dia por um usuario", answer: 80 },
      { text: "Numero de satelites GPS em orbita", answer: 31 },
    ],
  },
  {
    id: 19, theme: "MEDICINA", patoPoints: 2,
    questions: [
      { text: "Numero de ossos no corpo humano adulto", answer: 206 },
      { text: "Litros de sangue no corpo humano", answer: 5 },
      { text: "Batimentos cardiacos medios por minuto em repouso", answer: 70 },
      { text: "Numero de neuronios no cerebro (bilhoes)", answer: 86 },
      { text: "Temperatura corporal normal (Celsius)", answer: 37 },
      { text: "Porcentagem de agua no corpo humano", answer: 60 },
      { text: "Numero de transplantes de orgaos realizados por ano no mundo (milhares)", answer: 150 },
      { text: "Numero de vacinas no calendario basico infantil brasileiro", answer: 15 },
      { text: "Anos de estudo para se formar em medicina no Brasil", answer: 6 },
      { text: "Numero de litros de sangue que os rins filtram por dia", answer: 180 },
      { text: "Batimentos cardiacos totais por dia (media, milhares)", answer: 100 },
      { text: "Numero de cromossomos humanos", answer: 46 },
      { text: "Tempo medio de uma cirurgia de apendicite (minutos)", answer: 60 },
      { text: "Porcentagem de pessoas que tem tipo sanguineo O+", answer: 36 },
      { text: "Numero de dentes em um adulto com todos os sisos", answer: 32 },
      { text: "Numero de especialidades medicas reconhecidas no Brasil", answer: 55 },
    ],
  },
  {
    id: 20, theme: "PETS", patoPoints: 2,
    questions: [
      { text: "Numero de caes no Brasil (milhoes, 2025)", answer: 62 },
      { text: "Numero de racas de gatos reconhecidas", answer: 73 },
      { text: "Idade maxima registrada de um cao (anos)", answer: 31 },
      { text: "Numero de dentes de um cao adulto", answer: 42 },
      { text: "Peso do maior cao do mundo (kg)", answer: 155 },
      { text: "Altura do menor cao do mundo (cm)", answer: 10 },
      { text: "Numero de gatos no Brasil (milhoes)", answer: 34 },
      { text: "Numero de racas de caes reconhecidas", answer: 360 },
      { text: "Tempo de gestacao de uma cadela (dias)", answer: 63 },
      { text: "Gasto medio mensal com um cao no Brasil (reais)", answer: 350 },
      { text: "Anos de vida media de um gato domestico", answer: 15 },
      { text: "Numero de bigodes de um gato (media)", answer: 24 },
      { text: "Numero de paises onde caes sao o pet numero um", answer: 40 },
      { text: "Porcentagem de lares brasileiros com pets", answer: 46 },
      { text: "Numero medio de filhotes em uma ninhada de Golden Retriever", answer: 8 },
      { text: "Numero de huesos do corpo do gato", answer: 230 },
    ],
  },
  {
    id: 21, theme: "DINHEIRO", patoPoints: 3,
    questions: [
      { text: "Fortuna de Jeff Bezos em 2025 (bilhoes de dolares)", answer: 200 },
      { text: "Numero de notas de dolar em circulacao no mundo (bilhoes)", answer: 54 },
      { text: "Ano de criacao do Bitcoin", answer: 2009 },
      { text: "Preco do item mais caro ja vendido no eBay (milhoes)", answer: 4.9 },
      { text: "Numero de centavos na moeda de maior valor facial ja cunhada", answer: 100000000 },
      { text: "Salario minimo mensal no Brasil em 2025 (reais)", answer: 1518 },
      { text: "Numero de bilionarios no mundo (2025)", answer: 2781 },
      { text: "Valor de mercado da Apple (trilhoes de dolares)", answer: 3 },
      { text: "Porcentagem de brasileiros endividados (2025)", answer: 77 },
      { text: "Numero de cedulas de real em circulacao (bilhoes)", answer: 7 },
      { text: "Ano de criacao do Pix", answer: 2020 },
      { text: "Numero de transacoes diarias via Pix (milhoes)", answer: 160 },
      { text: "Maior nota de dinheiro ja impressa no mundo (valor facial em dolares)", answer: 100000 },
      { text: "Numero de agencias bancarias no Brasil", answer: 18000 },
      { text: "Preco do carro mais caro do mundo (milhoes de dolares)", answer: 28 },
      { text: "Numero medio de cartoes de credito por brasileiro", answer: 3 },
    ],
  },
  {
    id: 22, theme: "GUERRAS", patoPoints: 3,
    questions: [
      { text: "Dias que durou a Segunda Guerra Mundial", answer: 2194 },
      { text: "Numero estimado de mortos na Primeira Guerra (milhoes)", answer: 20 },
      { text: "Numero de paises envolvidos na Segunda Guerra", answer: 61 },
      { text: "Anos que durou a Guerra dos Cem Anos", answer: 116 },
      { text: "Numero de bombas atomicas ja detonadas (testes + uso)", answer: 2056 },
      { text: "Tamanho do exercito de Terracota (estatuas)", answer: 8000 },
      { text: "Numero total de mortos na Segunda Guerra (milhoes)", answer: 70 },
      { text: "Ano do fim da Guerra Fria", answer: 1991 },
      { text: "Numero de paises com armas nucleares (2025)", answer: 9 },
      { text: "Dias que durou a Guerra dos Seis Dias", answer: 6 },
      { text: "Numero de soldados brasileiros na Segunda Guerra (milhares)", answer: 25 },
      { text: "Anos que durou a Guerra do Vietna", answer: 20 },
      { text: "Numero de guerras mundiais ocorridas", answer: 2 },
      { text: "Numero de tripulantes do Enola Gay (bombardeiro de Hiroshima)", answer: 12 },
      { text: "Ano da Batalha de Waterloo", answer: 1815 },
      { text: "Numero de nacoes fundadoras da ONU apos a Segunda Guerra", answer: 51 },
    ],
  },
  {
    id: 23, theme: "AVIACAO", patoPoints: 2,
    questions: [
      { text: "Velocidade de cruzeiro de um Boeing 747 (km/h)", answer: 920 },
      { text: "Numero de voos comerciais por dia no mundo", answer: 100000 },
      { text: "Altura de voo de um aviao comercial padrao (pes)", answer: 35000 },
      { text: "Comprimento da maior pista de pouso do mundo (km)", answer: 5.5 },
      { text: "Numero de passageiros maximo do Airbus A380", answer: 853 },
      { text: "Ano do primeiro voo dos irmaos Wright", answer: 1903 },
      { text: "Numero de aeroportos no Brasil", answer: 2700 },
      { text: "Velocidade do aviao mais rapido do mundo (SR-71 Blackbird, km/h)", answer: 3530 },
      { text: "Numero de turbinas no maior aviao do mundo (Antonov An-225)", answer: 6 },
      { text: "Tempo do voo comercial mais longo do mundo (horas)", answer: 19 },
      { text: "Numero de passageiros transportados por ano no mundo (bilhoes)", answer: 4.5 },
      { text: "Numero de saidas de emergencia em um Boeing 747", answer: 10 },
      { text: "Comprimento de um Airbus A380 (metros)", answer: 73 },
      { text: "Numero de comissarios minimo por voo (a cada 50 passageiros)", answer: 1 },
      { text: "Numero de pilotos na cabine de um voo comercial longo", answer: 3 },
      { text: "Ano de fundacao da Embraer", answer: 1969 },
    ],
  },
  {
    id: 24, theme: "MONTANHAS", patoPoints: 2,
    questions: [
      { text: "Altura do Monte Everest (metros)", answer: 8849 },
      { text: "Numero de pessoas que escalaram o Everest (ate 2025)", answer: 12000 },
      { text: "Numero de montanhas com mais de 8000m", answer: 14 },
      { text: "Idade estimada do Monte Everest (milhoes de anos)", answer: 60 },
      { text: "Temperatura minima no topo do Everest (Celsius negativos)", answer: 60 },
      { text: "Numero de mortes no Everest desde 1922", answer: 330 },
      { text: "Numero de montanhas nos Andes com mais de 6000m", answer: 100 },
      { text: "Altura do Monte Kilimanjaro (metros)", answer: 5895 },
      { text: "Altura do Monte Fuji (metros)", answer: 3776 },
      { text: "Numero de paises que dividem os Alpes", answer: 8 },
      { text: "Pico mais alto do Brasil (Pico da Neblina, metros)", answer: 2995 },
      { text: "Numero de acampamentos base no Everest", answer: 4 },
      { text: "Preco medio para escalar o Everest (milhares de dolares)", answer: 50 },
      { text: "Comprimento da Cordilheira dos Andes (km)", answer: 7000 },
      { text: "Ano da primeira escalada do Everest", answer: 1953 },
      { text: "Numero de vulcoes ativos nos Andes", answer: 50 },
    ],
  },
  {
    id: 25, theme: "LITERATURA", patoPoints: 3,
    questions: [
      { text: "Numero de palavras em Dom Quixote (milhares)", answer: 380 },
      { text: "Numero de livros da Biblia", answer: 66 },
      { text: "Idiomas em que Harry Potter foi traduzido", answer: 80 },
      { text: "Numero de pecas escritas por Shakespeare", answer: 39 },
      { text: "Preco do manuscrito mais caro ja vendido (milhoes de dolares)", answer: 30 },
      { text: "Milhoes de copias vendidas de 'O Pequeno Principe'", answer: 200 },
      { text: "Numero de paginas de 'Guerra e Paz'", answer: 1225 },
      { text: "Idade de Monteiro Lobato ao publicar seu primeiro livro", answer: 36 },
      { text: "Numero de livros da saga Harry Potter", answer: 7 },
      { text: "Numero de premios Jabuti entregues por ano", answer: 20 },
      { text: "Numero de personagens em 'Os Miseraveis'", answer: 100 },
      { text: "Anos que James Joyce levou para escrever 'Ulisses'", answer: 7 },
      { text: "Numero total de copias da Biblia vendidas (bilhoes)", answer: 5 },
      { text: "Paginas do livro brasileiro mais vendido (O Alquimista, media)", answer: 160 },
      { text: "Numero de contos dos irmaos Grimm", answer: 200 },
      { text: "Numero de livros na biblioteca do Congresso dos EUA (milhoes)", answer: 170 },
    ],
  },
  {
    id: 26, theme: "VIDEO GAMES", patoPoints: 2,
    questions: [
      { text: "Numero de copias vendidas de Minecraft (milhoes)", answer: 300 },
      { text: "Numero de jogadores ativos de Fortnite (milhoes)", answer: 650 },
      { text: "Ano de lancamento do primeiro PlayStation", answer: 1994 },
      { text: "Bits do Super Nintendo", answer: 16 },
      { text: "Recorde de velocidade no Super Mario 64 (minutos)", answer: 6 },
      { text: "Numero de Pokemon na Pokedex nacional (ate 2025)", answer: 1025 },
      { text: "Numero de fases de Super Mario World", answer: 72 },
      { text: "Numero de jogos ja lancados para PlayStation 2", answer: 4000 },
      { text: "Preco do PlayStation 5 no lancamento no Brasil (reais)", answer: 5000 },
      { text: "Numero medio de horas para zerar The Witcher 3", answer: 50 },
      { text: "Numero de consoles de videogame ja lancados na historia", answer: 50 },
      { text: "Numero de personagens jogaveis em Super Smash Bros. Ultimate", answer: 89 },
      { text: "Numero de missoes principais de GTA V", answer: 69 },
      { text: "Duracao do jogo mais longo da historia (The Longing, dias)", answer: 400 },
      { text: "Numero de mundos em Super Mario Bros. 3", answer: 8 },
      { text: "Ano de lancamento do Atari 2600", answer: 1977 },
    ],
  },
  {
    id: 27, theme: "INSETOS", patoPoints: 2,
    questions: [
      { text: "Numero de especies de formigas conhecidas", answer: 12000 },
      { text: "Numero de olhos de uma abelha", answer: 5 },
      { text: "Velocidade de voo de uma libelula (km/h)", answer: 60 },
      { text: "Peso que uma formiga pode carregar (vezes o proprio peso)", answer: 50 },
      { text: "Numero de pernas de uma lacraia gigante", answer: 42 },
      { text: "Milhoes de anos que as baratas existem", answer: 300 },
      { text: "Numero de especies de besouros conhecidas", answer: 400000 },
      { text: "Batidas de asas de um mosquito por segundo", answer: 600 },
      { text: "Numero de insetos estimados no mundo (quintilhoes)", answer: 10 },
      { text: "Numero de pernas de um inseto", answer: 6 },
      { text: "Numero de asas de uma abelha", answer: 4 },
      { text: "Tempo de vida de uma mosca domestica (dias)", answer: 28 },
      { text: "Numero de formigas em uma colonia de sauvas (milhoes)", answer: 8 },
      { text: "Distancia que um enxame de gafanhotos pode viajar por dia (km)", answer: 150 },
      { text: "Numero de especies de borboletas no Brasil", answer: 3500 },
      { text: "Tempo de vida de uma efemera adulta (horas)", answer: 24 },
    ],
  },
  {
    id: 28, theme: "BEBIDAS", patoPoints: 2,
    questions: [
      { text: "Xicaras de cafe consumidas por dia no mundo (bilhoes)", answer: 2.5 },
      { text: "Numero de garrafas de Coca-Cola vendidas por dia (milhoes)", answer: 2000 },
      { text: "Porcentagem de agua em uma cerveja", answer: 90 },
      { text: "Numero de variedades de uva para vinho", answer: 10000 },
      { text: "Preco do drinque mais caro do mundo (milhares de dolares)", answer: 15 },
      { text: "Idade minima para beber na maioria dos paises da Europa", answer: 18 },
      { text: "Litros de cerveja consumidos por ano no Brasil (bilhoes)", answer: 14 },
      { text: "Numero de destilarias de whisky na Escocia", answer: 140 },
      { text: "Anos de envelhecimento do whisky mais velho ja vendido", answer: 81 },
      { text: "Numero de ingredientes no Bloody Mary original", answer: 7 },
      { text: "Temperatura ideal para servir vinho tinto (Celsius)", answer: 18 },
      { text: "Numero de calorias em uma lata de Coca-Cola (350ml)", answer: 140 },
      { text: "Porcentagem do mercado de cerveja no Brasil da Ambev", answer: 60 },
      { text: "Numero de uvas para fazer uma garrafa de vinho (media)", answer: 600 },
      { text: "Numero de paises produtores de vinho", answer: 70 },
      { text: "Teor alcoolico de uma cachaça artesanal tipica (porcentagem)", answer: 42 },
    ],
  },
  {
    id: 29, theme: "RECORDES MUNDIAIS", patoPoints: 3,
    questions: [
      { text: "Numero de malabares simultaneos (recorde mundial)", answer: 14 },
      { text: "Unhas mais longas do mundo acumuladas (metros)", answer: 13 },
      { text: "Maior numero de filhos de uma mulher (recordado)", answer: 69 },
      { text: "Tempo sem dormir recorde (horas)", answer: 264 },
      { text: "Numero de pessoas no maior abraco coletivo", answer: 10000 },
      { text: "Distancia do maior arremesso de anao ja registrado (metros)", answer: 4 },
      { text: "Maior numero de quebras de tijolos em um minuto", answer: 124 },
      { text: "Comprimento da maior pizza do mundo (metros)", answer: 1250 },
      { text: "Numero de hot dogs comidos em 10 minutos (recorde masculino)", answer: 76 },
      { text: "Idade da pessoa mais velha ja registrada (anos)", answer: 122 },
      { text: "Maior numero de pessoas fantasiadas de Smurf em um lugar", answer: 1012 },
      { text: "Comprimento da maior barba do mundo (metros)", answer: 5.3 },
      { text: "Numero de tatuagens na pessoa mais tatuada do mundo", answer: 1000 },
      { text: "Tempo de beijo mais longo do mundo (horas)", answer: 58 },
      { text: "Maior distancia percorrida engatinhando (km)", answer: 12 },
      { text: "Numero de pessoas na maior aula de danca do mundo", answer: 10000 },
    ],
  },
  {
    id: 30, theme: "RELIGIAO", patoPoints: 2,
    questions: [
      { text: "Porcentagem de cristaos no mundo", answer: 31 },
      { text: "Porcentagem de muculmanos no mundo", answer: 25 },
      { text: "Numero de papas na historia da Igreja Catolica", answer: 266 },
      { text: "Numero de idiomas em que a Biblia foi traduzida", answer: 700 },
      { text: "Porcentagem de hindus no mundo", answer: 15 },
      { text: "Numero de deuses no hinduismo (aproximado)", answer: 330000000 },
      { text: "Numero de mandamentos nos Dez Mandamentos", answer: 10 },
      { text: "Numero de religioes principais no mundo", answer: 5 },
      { text: "Porcentagem de ateus no mundo", answer: 7 },
      { text: "Numero de suratas (capitulos) no Alcorao", answer: 114 },
      { text: "Ano do primeiro concilio da Igreja Catolica (Niceia)", answer: 325 },
      { text: "Numero de cardeais no Colegio Cardinalicio", answer: 230 },
      { text: "Porcentagem de budistas no mundo", answer: 7 },
      { text: "Numero de apostolos de Jesus", answer: 12 },
      { text: "Numero de livros no Antigo Testamento", answer: 39 },
      { text: "Numero de visitantes anuais no Vaticano (milhoes)", answer: 5 },
    ],
  },
  {
    id: 31, theme: "PLANETA TERRA", patoPoints: 3,
    questions: [
      { text: "Idade da Terra (bilhoes de anos)", answer: 4.5 },
      { text: "Porcentagem de agua doce na Terra", answer: 3 },
      { text: "Raio da Terra (km)", answer: 6371 },
      { text: "Numero de vulcoes ativos no mundo", answer: 1500 },
      { text: "Velocidade de rotacao da Terra no Equador (km/h)", answer: 1670 },
      { text: "Porcentagem de especies ja extintas", answer: 99 },
      { text: "Numero de camadas da Terra", answer: 4 },
      { text: "Diametro da Terra (km)", answer: 12742 },
      { text: "Numero de oceanos no planeta", answer: 5 },
      { text: "Porcentagem de oxigenio na atmosfera terrestre", answer: 21 },
      { text: "Distancia da Terra ao Sol (milhoes de km)", answer: 150 },
      { text: "Numero de terremotos detectados por ano", answer: 500000 },
      { text: "Idade da rocha mais antiga ja encontrada (bilhoes de anos)", answer: 4.4 },
      { text: "Numero de especies de seres vivos estimadas na Terra (milhoes)", answer: 8.7 },
      { text: "Velocidade de translacao da Terra ao redor do Sol (km/h)", answer: 107000 },
      { text: "Porcentagem da Terra que e desertica", answer: 33 },
    ],
  },
  {
    id: 32, theme: "CELULARES", patoPoints: 2,
    questions: [
      { text: "Numero de smartphones no mundo (bilhoes, 2025)", answer: 7 },
      { text: "Preco do primeiro iPhone nos EUA (dolares)", answer: 499 },
      { text: "Peso do primeiro celular Motorola DynaTAC (kg)", answer: 1.1 },
      { text: "Megapixels da camera do primeiro iPhone", answer: 2 },
      { text: "Numero de chips em um iPhone 15 Pro (bilhoes de transistores)", answer: 19 },
      { text: "Tempo medio de tela diario de um adolescente (horas)", answer: 7 },
      { text: "Numero de apps na App Store (milhoes)", answer: 2 },
      { text: "Porcentagem de usuarios de Android no Brasil", answer: 85 },
      { text: "Numero de fabricantes de celular no mundo", answer: 100 },
      { text: "Tempo medio para trocar de celular (anos)", answer: 3 },
      { text: "Capacidade maxima de bateria em um celular atual (mAh)", answer: 7000 },
      { text: "Numero medio de fotos tiradas por dia por usuario", answer: 8 },
      { text: "Ano do primeiro celular com camera", answer: 2000 },
      { text: "Numero de brasileiros com smartphone (milhoes)", answer: 160 },
      { text: "Numero medio de apps instalados por usuario", answer: 80 },
      { text: "Preco medio de um celular basico no Brasil (reais)", answer: 1200 },
    ],
  },
  {
    id: 33, theme: "CIENCIA", patoPoints: 3,
    questions: [
      { text: "Numero de elementos na tabela periodica", answer: 118 },
      { text: "Velocidade da luz (km/s)", answer: 300000 },
      { text: "Numero de atomos no universo observavel (potencia de 10)", answer: 80 },
      { text: "Temperatura do zero absoluto (Celsius negativos)", answer: 273 },
      { text: "Numero de Premios Nobel em ciencias entregues ate 2025", answer: 653 },
      { text: "Anos desde a publicacao de 'Origem das Especies' de Darwin", answer: 166 },
      { text: "Numero de leis de Newton", answer: 3 },
      { text: "Constante gravitacional (aproximada, metros por segundo ao quadrado)", answer: 10 },
      { text: "Numero de particulas no Modelo Padrao da fisica", answer: 17 },
      { text: "Idade do universo (bilhoes de anos)", answer: 13.8 },
      { text: "Numero de atomos em uma molecula de agua", answer: 3 },
      { text: "Numero de laboratorios CERN no mundo", answer: 1 },
      { text: "Temperatura media do universo (Kelvin)", answer: 2.7 },
      { text: "Numero de genomas humanos ja sequenciados (milhoes)", answer: 100 },
      { text: "Numero de eletrons no atomo de oxigenio", answer: 8 },
      { text: "Ano da primeira clonagem de um mamifero (Dolly)", answer: 1996 },
    ],
  },
  {
    id: 34, theme: "MODA", patoPoints: 2,
    questions: [
      { text: "Tamanho do salto mais alto ja feito (cm)", answer: 30 },
      { text: "Numero de pares de tenis vendidos por ano no mundo (bilhoes)", answer: 23 },
      { text: "Preco do vestido mais caro ja feito (milhoes de dolares)", answer: 30 },
      { text: "Numero de desfiles na Semana de Moda de Paris", answer: 90 },
      { text: "Ano de fundacao da Louis Vuitton", answer: 1854 },
      { text: "Porcentagem do mercado de luxo controlado pela LVMH", answer: 25 },
      { text: "Numero de marcas no maior grupo de moda do mundo (Inditex)", answer: 8 },
      { text: "Preco medio de um jeans de grife no Brasil (reais)", answer: 500 },
      { text: "Numero de paises que participam da Fashion Week de Paris", answer: 50 },
      { text: "Numero de pecas em uma colecao de alta-costura", answer: 50 },
      { text: "Ano do primeiro desfile de moda da historia", answer: 1858 },
      { text: "Numero de funcionarios da industria textil no Brasil (milhoes)", answer: 1.5 },
      { text: "Porcentagem do algodao mundial consumido pela industria da moda", answer: 60 },
      { text: "Numero de pares de sapato de Imelda Marcos", answer: 3000 },
      { text: "Tamanho medio do guarda-roupa feminino brasileiro (pecas)", answer: 200 },
      { text: "Numero de edicoes da Vogue Brasil por ano", answer: 12 },
    ],
  },
  {
    id: 35, theme: "CURIOSIDADES", patoPoints: 2,
    questions: [
      { text: "Numero de linguas de sogra vendidas por ano no Brasil (milhoes)", answer: 25 },
      { text: "Velocidade de um espirro (km/h)", answer: 160 },
      { text: "Porcentagem de canhotos no mundo", answer: 10 },
      { text: "Numero de vezes que piscamos por dia (milhares)", answer: 28 },
      { text: "Comprimento total de vasos sanguineos no corpo humano (km)", answer: 100000 },
      { text: "Numero de saborizantes em um Doritos Nacho Cheese", answer: 30 },
      { text: "Numero de nucleos em uma celula de figado", answer: 2 },
      { text: "Numero de cores em um arco-iris", answer: 7 },
      { text: "Velocidade de crescimento do cabelo (cm por mes)", answer: 1.25 },
      { text: "Numero medio de passos dados por dia por uma pessoa", answer: 5000 },
      { text: "Numero de letras do alfabeto havaiano", answer: 12 },
      { text: "Tempo que uma pessoa passa dormindo ao longo da vida (anos)", answer: 25 },
      { text: "Numero de vezes que o coracao bate ao longo da vida (bilhoes)", answer: 2.5 },
      { text: "Peso total de pele renovada ao longo da vida (kg)", answer: 20 },
      { text: "Numero de mensagens de texto enviadas por segundo no mundo", answer: 200000 },
      { text: "Porcentagem de pessoas que ja quebraram um osso na vida", answer: 50 },
    ],
  },
  {
    id: 36, theme: "CONSTRUCAO", patoPoints: 2,
    questions: [
      { text: "Andares do maior arranha-ceu do Brasil (One Tower)", answer: 84 },
      { text: "Numero de tuneis na Muralha da China", answer: 0 },
      { text: "Comprimento da Grande Muralha da China (km)", answer: 21196 },
      { text: "Numero de operarios que construiram Brasilia", answer: 60000 },
      { text: "Anos para construir a Sagrada Familia (ate hoje)", answer: 143 },
      { text: "Numero de pontes em Veneza", answer: 391 },
      { text: "Altura do predio mais alto do mundo (Burj Khalifa, metros)", answer: 828 },
      { text: "Numero de tijolos no Empire State Building (milhoes)", answer: 10 },
      { text: "Numero de apartamentos em um predio do programa Minha Casa Minha Vida (media)", answer: 200 },
      { text: "Numero de cidades brasileiras com mais de 1 milhao de habitantes", answer: 17 },
      { text: "Comprimento da ponte Rio-Niteroi (km)", answer: 13 },
      { text: "Numero de operarios que trabalharam na Sagrada Familia (pico)", answer: 200 },
      { text: "Numero de anos para construir o Castelo de Neuschwanstein", answer: 23 },
      { text: "Numero de escavadeiras na construcao do Canal do Panama", answer: 100 },
      { text: "Numero de barragens no Brasil", answer: 25000 },
      { text: "Numero de elevadores no Burj Khalifa", answer: 57 },
    ],
  },
  {
    id: 37, theme: "CATASTROFES", patoPoints: 3,
    questions: [
      { text: "Magnitude do terremoto mais forte ja registrado", answer: 9.5 },
      { text: "Numero de mortos na Peste Negra (milhoes, Europa)", answer: 50 },
      { text: "Ano da erupcao do Vesuvio que destruiu Pompeia", answer: 79 },
      { text: "Altura do maior tsunami registrado (metros)", answer: 524 },
      { text: "Numero de mortos no Titanic", answer: 1514 },
      { text: "Diametro do meteoro que extinguiu os dinossauros (km)", answer: 10 },
      { text: "Numero de mortos no acidente nuclear de Chernobyl (oficial)", answer: 31 },
      { text: "Numero de dias do incendio na Amazonia em 2019 (pico)", answer: 30 },
      { text: "Ano do terremoto de Lisboa", answer: 1755 },
      { text: "Numero de paises afetados pelo tsunami de 2004", answer: 14 },
      { text: "Numero de mortos na bomba de Hiroshima", answer: 140000 },
      { text: "Indice de explosividade vulcanica do Krakatoa (maximo 8)", answer: 6 },
      { text: "Numero de edificios que desabaram no 11 de setembro", answer: 3 },
      { text: "Numero de mortos no rompimento da barragem de Brumadinho", answer: 270 },
      { text: "Ano do Grande Incendio de Chicago", answer: 1871 },
      { text: "Numero de pessoas desabrigadas pelo furacao Katrina (milhares)", answer: 400 },
    ],
  },
  {
    id: 38, theme: "REDES SOCIAIS", patoPoints: 2,
    questions: [
      { text: "Usuarios mensais do Instagram (bilhoes)", answer: 2 },
      { text: "Numero maximo de caracteres em um tweet (em 2025)", answer: 280 },
      { text: "Ano de fundacao do TikTok", answer: 2016 },
      { text: "Videos enviados por minuto no YouTube (horas)", answer: 500 },
      { text: "Usuarios do LinkedIn (milhoes)", answer: 1000 },
      { text: "Numero de funcionarios do Facebook/Meta (milhares)", answer: 70 },
      { text: "Numero de usuarios ativos do WhatsApp (bilhoes)", answer: 2.7 },
      { text: "Numero de stories postados no Instagram por dia (milhoes)", answer: 500 },
      { text: "Tempo medio gasto por dia no TikTok (minutos)", answer: 95 },
      { text: "Numero máximo de fotos por post no Instagram (carrossel)", answer: 10 },
      { text: "Ano de fundacao do Twitter (atual X)", answer: 2006 },
      { text: "Porcentagem de brasileiros que usam WhatsApp", answer: 96 },
      { text: "Numero de usuarios do Telegram (milhoes)", answer: 900 },
      { text: "Duracao maxima de um video no TikTok (minutos)", answer: 10 },
      { text: "Numero de likes no post mais curtido do Instagram (milhoes)", answer: 20 },
      { text: "Numero medio de seguidores de um usuario brasileiro no Instagram", answer: 300 },
    ],
  },
  {
    id: 39, theme: "PIRATAS", patoPoints: 3,
    questions: [
      { text: "Seculo da Era de Ouro da Pirataria", answer: 18 },
      { text: "Numero de canhoes no Queen Anne's Revenge (Barba Negra)", answer: 40 },
      { text: "Numero de esposas de Barba Negra", answer: 14 },
      { text: "Anos que durou a Era de Ouro da Pirataria", answer: 100 },
      { text: "Numero de capitulos do Codigo dos Piratas", answer: 9 },
      { text: "Porcentagem de piratas que morriam de doenca (nao em batalha)", answer: 50 },
      { text: "Numero de tripulantes no navio de Barba Negra", answer: 300 },
      { text: "Numero de filmes da franquia Piratas do Caribe", answer: 5 },
      { text: "Numero de bandeiras piratas diferentes ja documentadas", answer: 100 },
      { text: "Comprimento medio de um navio pirata (metros)", answer: 30 },
      { text: "Numero de mares que os piratas do Caribe navegavam", answer: 1 },
      { text: "Numero de olhos de um pirata tipico (estereotipo)", answer: 1 },
      { text: "Numero de pernas de pau usadas na epoca (raro mas real)", answer: 20 },
      { text: "Ano do fim oficial da Era de Ouro da Pirataria", answer: 1726 },
      { text: "Numero de piratas famosos na historia", answer: 50 },
      { text: "Valor do tesouro de Barba Negra (milhoes de dolares atuais)", answer: 15 },
    ],
  },
  {
    id: 40, theme: "SAMBA & CARNAVAL", patoPoints: 2,
    questions: [
      { text: "Numero de escolas de samba no Grupo Especial do Rio", answer: 12 },
      { text: "Minutos de desfile de cada escola de samba no RJ", answer: 75 },
      { text: "Numero de componentes em uma escola de samba (media)", answer: 3500 },
      { text: "Turistas no carnaval do Rio por ano (milhoes)", answer: 2 },
      { text: "Preco da fantasia mais cara da Sapucai (milhares de reais)", answer: 50 },
      { text: "Ano do primeiro desfile oficial de carnaval no Rio", answer: 1932 },
      { text: "Numero de alas em uma escola de samba", answer: 30 },
      { text: "Numero de jurados no julgamento do desfile do Rio", answer: 40 },
      { text: "Numero de notas possiveis para cada quesito", answer: 10 },
      { text: "Comprimento da Sapucai (metros)", answer: 700 },
      { text: "Numero de titulos da Mangueira", answer: 24 },
      { text: "Numero de carros alegoricos por escola", answer: 6 },
      { text: "Numero de ritmistas na bateria de uma escola (media)", answer: 300 },
      { text: "Numero de dias de desfile do Grupo Especial do Rio", answer: 3 },
      { text: "Numero de turistas no carnaval de Salvador (milhoes)", answer: 3 },
      { text: "Numero de escolas de samba fundadoras do carnaval do Rio", answer: 5 },
    ],
  },
  {
    id: 41, theme: "COPA DO MUNDO", patoPoints: 3,
    questions: [
      { text: "Numero de gols na carreira de Copa de Miroslav Klose", answer: 16 },
      { text: "Numero de paises-sede diferentes ate 2022", answer: 17 },
      { text: "Capacidade do maior estadio de Copa (Maracana em 1950)", answer: 200000 },
      { text: "Numero de jogos em uma Copa de 32 times", answer: 64 },
      { text: "Premiacao do campeao da Copa 2022 (milhoes de dolares)", answer: 42 },
      { text: "Numero de cartoes amarelos na Copa 2022", answer: 227 },
      { text: "Numero de gols na Copa do Mundo 2022", answer: 172 },
      { text: "Numero de paises que participarao da Copa de 2026", answer: 48 },
      { text: "Numero de titulos do Brasil em Copas do Mundo", answer: 5 },
      { text: "Numero de paises que ja sediaram a Copa", answer: 17 },
      { text: "Maior goleada da historia das Copas (Hungria x El Salvador)", answer: 9 },
      { text: "Numero de estadios na Copa do Catar", answer: 8 },
      { text: "Numero de vezes que a Italia ganhou a Copa", answer: 4 },
      { text: "Numero de jogadores no elenco campeao de 2022 (Argentina)", answer: 26 },
      { text: "Numero de bolas de ouro da Copa ganhas por Messi", answer: 2 },
      { text: "Numero de edicoes da Copa do Mundo Feminina (ate 2023)", answer: 9 },
    ],
  },
  {
    id: 42, theme: "ARTES", patoPoints: 2,
    questions: [
      { text: "Preco da pintura mais cara ja vendida (milhoes de dolares)", answer: 450 },
      { text: "Numero de obras de Van Gogh", answer: 900 },
      { text: "Anos que Leonardo da Vinci pintou a Mona Lisa", answer: 4 },
      { text: "Peso da estatua do Cristo Redentor (toneladas)", answer: 1145 },
      { text: "Altura da estatua do Cristo Redentor (metros)", answer: 38 },
      { text: "Numero de museus no Louvre", answer: 1 },
      { text: "Numero de obras de Pablo Picasso", answer: 50000 },
      { text: "Numero de visitantes anuais do Louvre (milhoes)", answer: 10 },
      { text: "Numero de paises na Bienal de Veneza", answer: 90 },
      { text: "Numero de afrescos na Capela Sistina", answer: 9 },
      { text: "Numero de bailarinos na companhia do Bolshoi", answer: 200 },
      { text: "Numero de sinfonias compostas por Mozart", answer: 41 },
      { text: "Altura do David de Michelangelo (metros)", answer: 5 },
      { text: "Numero de quadros no acervo do MASP", answer: 11000 },
      { text: "Numero de esculturas de Rodin no mundo", answer: 700 },
      { text: "Numero de instrumentos em uma orquestra sinfonica", answer: 100 },
    ],
  },
  {
    id: 43, theme: "PLANTAS", patoPoints: 2,
    questions: [
      { text: "Numero de especies de arvores na Amazonia", answer: 16000 },
      { text: "Idade da arvore mais velha do mundo (anos)", answer: 5000 },
      { text: "Altura da maior arvore do mundo (metros)", answer: 116 },
      { text: "Numero de flores que uma abelha visita por dia", answer: 5000 },
      { text: "Peso da maior abobora ja cultivada (kg)", answer: 1247 },
      { text: "Porcentagem de oxigenio produzido por algas marinhas", answer: 50 },
      { text: "Numero de especies de plantas conhecidas no mundo (milhares)", answer: 400 },
      { text: "Tempo de germinacao de uma semente de feijao (dias)", answer: 5 },
      { text: "Numero de folhas de uma arvore adulta media", answer: 200000 },
      { text: "Altura da maior flor do mundo (Rafflesia, cm)", answer: 100 },
      { text: "Numero de petalas da flor de cerejeira", answer: 5 },
      { text: "Comprimento maximo da raiz de uma arvore (metros)", answer: 50 },
      { text: "Numero de graos em uma espiga de milho (media)", answer: 800 },
      { text: "Porcentagem de plantas que dependem de polinizadores", answer: 87 },
      { text: "Numero de especies de cactus conhecidas", answer: 2000 },
      { text: "Velocidade de crescimento do bambu por dia (cm)", answer: 91 },
    ],
  },
  {
    id: 44, theme: "PSICOLOGIA", patoPoints: 3,
    questions: [
      { text: "Numero medio de sonhos por noite", answer: 5 },
      { text: "Porcentagem de sonhos que esquecidos em 5 minutos", answer: 50 },
      { text: "Horas de sono recomendadas para adultos", answer: 8 },
      { text: "Numero de fobias catalogadas", answer: 500 },
      { text: "Porcentagem da populacao com aracnofobia", answer: 5 },
      { text: "QI medio da populacao mundial", answer: 100 },
      { text: "Numero de emocoes basicas segundo Paul Ekman", answer: 6 },
      { text: "Porcentagem da comunicacao que e nao verbal", answer: 70 },
      { text: "Numero de tipos de personalidade no MBTI", answer: 16 },
      { text: "Duracao media da memoria de curto prazo (segundos)", answer: 20 },
      { text: "Numero de estagios do sono", answer: 4 },
      { text: "Porcentagem de pessoas com depressao no mundo", answer: 5 },
      { text: "Numero de horas de terapia necessarias para mudanca media de comportamento", answer: 20 },
      { text: "Idade media do inicio da formacao de memorias de longo prazo (anos)", answer: 3 },
      { text: "Porcentagem da populacao introvertida", answer: 40 },
      { text: "Numero de neuronios espelho descobertos (area de Broca, milhoes)", answer: 10 },
    ],
  },
  {
    id: 45, theme: "SHOPPING", patoPoints: 2,
    questions: [
      { text: "Numero de lojas no maior shopping do Brasil", answer: 600 },
      { text: "Porcentagem de compras feitas online no Brasil (2025)", answer: 15 },
      { text: "Numero de shoppings centers no Brasil", answer: 620 },
      { text: "Faturamento na Black Friday Brasil 2024 (bilhoes de reais)", answer: 8 },
      { text: "Tamanho do maior shopping do mundo (milhares de m2)", answer: 660 },
      { text: "Ano de abertura do primeiro shopping do Brasil", answer: 1966 },
      { text: "Numero de vagas de estacionamento no maior shopping do Brasil", answer: 10000 },
      { text: "Numero medio de visitantes por dia em um shopping grande", answer: 50000 },
      { text: "Numero de praças de alimentacao em um shopping tipico", answer: 1 },
      { text: "Numero de cinemas no maior complexo de cinema em shopping no Brasil", answer: 18 },
      { text: "Numero de lojas-ancora em um shopping medio (magazines grandes)", answer: 6 },
      { text: "Numero de andares no maior shopping do Brasil", answer: 5 },
      { text: "Porcentagem de vendas do varejo brasileiro que acontecem em shoppings", answer: 25 },
      { text: "Numero medio de Lojas Americanas em shoppings antes da crise", answer: 600 },
      { text: "Numero de shoppings na cidade de Sao Paulo", answer: 60 },
      { text: "Numero de funcionarios do maior shopping do Brasil", answer: 8000 },
    ],
  },
  {
    id: 46, theme: "FESTAS JUNINAS", patoPoints: 2,
    questions: [
      { text: "Numero de dias de festa junina em Campina Grande", answer: 30 },
      { text: "Altura da maior fogueira junina ja construida (metros)", answer: 40 },
      { text: "Numero de comidas tipicas listadas oficialmente", answer: 30 },
      { text: "Publico da maior festa junina do Brasil (milhoes)", answer: 2.5 },
      { text: "Numero de quadrilhas na final nacional de quadrilha junina", answer: 20 },
      { text: "Toneladas de milho consumidas nas festas juninas do Nordeste", answer: 3000 },
      { text: "Numero de santos homenageados nas festas juninas", answer: 3 },
      { text: "Dia de Sao Joao no calendario", answer: 24 },
      { text: "Numero de casais em uma quadrilha junina oficial", answer: 16 },
      { text: "Numero de barracas tipicas em uma grande festa junina", answer: 100 },
      { text: "Comprimento do maior pe de moleque ja feito (metros)", answer: 50 },
      { text: "Numero de cidades que realizam festa junina no Brasil", answer: 5000 },
      { text: "Numero de fogos de artificio na abertura de Caruaru", answer: 15 },
      { text: "Preco medio de um prato tipico em festa junina (reais)", answer: 25 },
      { text: "Numero de turistas em Campina Grande durante a festa (milhoes)", answer: 2 },
      { text: "Numero de bandas que se apresentam em Caruaru por ano", answer: 300 },
    ],
  },
  {
    id: 47, theme: "MISTERIOS", patoPoints: 3,
    questions: [
      { text: "Numero de pedras em Stonehenge", answer: 83 },
      { text: "Anos que o Triangulo das Bermudas e considerado misterio", answer: 80 },
      { text: "Profundidade do Lago Ness (metros)", answer: 230 },
      { text: "Numero de linhas de Nazca descobertas", answer: 300 },
      { text: "Peso das estatuas da Ilha de Pascoa (toneladas)", answer: 14 },
      { text: "Numero de sitios arqueologicos maias conhecidos", answer: 4400 },
      { text: "Ano do incidente de Roswell", answer: 1947 },
      { text: "Numero de ilhas que formam o Arquipelago das Bermudas", answer: 181 },
      { text: "Numero de esqueletos encontrados no navio Mary Celeste (navio fantasma)", answer: 0 },
      { text: "Numero de estatuas na Ilha de Pascoa (Moais)", answer: 887 },
      { text: "Anos desde a construcao de Stonehenge (milhares)", answer: 5 },
      { text: "Numero de avistamentos de OVNIs registrados por ano (milhares)", answer: 100 },
      { text: "Numero de pessoas desaparecidas no Triangulo das Bermudas", answer: 1000 },
      { text: "Numero de sitios arqueologicos Incas conhecidos", answer: 1000 },
      { text: "Numero de quipos Incas decifrados ate hoje", answer: 50 },
      { text: "Numero de objetos no manuscrito Voynich", answer: 200 },
    ],
  },
  {
    id: 48, theme: "FAMOSOS", patoPoints: 2,
    questions: [
      { text: "Seguidores de Cristiano Ronaldo no Instagram (milhoes)", answer: 650 },
      { text: "Numero de Grammys ganhos por Beyonce", answer: 32 },
      { text: "Idade de Morgan Freeman ao ganhar seu primeiro Oscar", answer: 67 },
      { text: "Numero de filmes com participacao de Stan Lee (cameo)", answer: 50 },
      { text: "Fortuna de Taylor Swift em 2025 (bilhoes de dolares)", answer: 1.6 },
      { text: "Numero de musicas gravadas por Roberto Carlos", answer: 600 },
      { text: "Numero de Oscars de Meryl Streep (indicacoes)", answer: 21 },
      { text: "Idade de Anitta ao lancar seu primeiro hit internacional", answer: 24 },
      { text: "Numero de filhos de Angelina Jolie", answer: 6 },
      { text: "Numero de albuns de estúdio de Michael Jackson", answer: 10 },
      { text: "Idade de Silvio Santos ao se aposentar", answer: 91 },
      { text: "Fortuna de Elon Musk em 2025 (bilhoes de dolares)", answer: 350 },
      { text: "Numero de premios Oscar de Walt Disney", answer: 26 },
      { text: "Numero de ex-esposas de Tom Cruise", answer: 3 },
      { text: "Idade de Xuxa ao estrear como apresentadora infantil", answer: 23 },
      { text: "Numero de seguidores do Instagram de Kylie Jenner (milhoes)", answer: 400 },
    ],
  },
  {
    id: 49, theme: "TRANSPORTE PUBLICO", patoPoints: 2,
    questions: [
      { text: "Numero de estacoes do metro de Sao Paulo", answer: 91 },
      { text: "Passageiros diarios do metro de Toquio (milhoes)", answer: 9 },
      { text: "Numero de cidades com metro no Brasil", answer: 7 },
      { text: "Velocidade maxima do trem-bala japones (km/h)", answer: 320 },
      { text: "Extensao total de ciclovias em Copenhagen (km)", answer: 500 },
      { text: "Numero de onibus em circulacao no Brasil (milhares)", answer: 400 },
      { text: "Numero de passageiros diarios do metro de Moscou (milhoes)", answer: 7 },
      { text: "Numero de linhas de metro em Sao Paulo", answer: 6 },
      { text: "Extensao total da malha ferroviaria brasileira (milhares de km)", answer: 30 },
      { text: "Numero de estacoes de BRT no Rio de Janeiro (Transoeste)", answer: 60 },
      { text: "Numero de passageiros diarios do onibus em Sao Paulo (milhoes)", answer: 6 },
      { text: "Velocidade media do metro de Sao Paulo (km/h)", answer: 60 },
      { text: "Preco da passagem de onibus em Sao Paulo (reais, 2025)", answer: 4.4 },
      { text: "Numero de cidades com VLT no Brasil", answer: 3 },
      { text: "Numero de ciclistas diarios em Copenhagen (milhares)", answer: 450 },
      { text: "Numero de taxis em Nova York", answer: 13000 },
    ],
  },
  {
    id: 50, theme: "DATAS & CALENDARIO", patoPoints: 3,
    questions: [
      { text: "Numero de dias em um ano bissexto", answer: 366 },
      { text: "Numero de meses com 31 dias", answer: 7 },
      { text: "Numero de fusos horarios na Russia", answer: 11 },
      { text: "Dias de atraso do calendario juliano por seculo", answer: 3 },
      { text: "Numero de anos em uma decada", answer: 10 },
      { text: "Numero de semanas em um ano", answer: 52 },
      { text: "Numero de dias uteis em um ano (media)", answer: 250 },
      { text: "Numero de meses no calendario judaico", answer: 12 },
      { text: "Numero de segundos em um dia", answer: 86400 },
      { text: "Ano da adocao do calendario gregoriano no Brasil", answer: 1582 },
      { text: "Numero de dias no mes de fevereiro em ano bissexto", answer: 29 },
      { text: "Numero de meses que tem 30 dias", answer: 4 },
      { text: "Numero de paises que nao usam o calendario gregoriano", answer: 4 },
      { text: "Numero de feriados nacionais no Brasil", answer: 12 },
      { text: "Ano da primeira Olímpiada da era moderna (calendario)", answer: 1896 },
      { text: "Numero de anos em um seculo", answer: 100 },
    ],
  },
  {
    id: 51, theme: "MITOLOGIA GREGA", patoPoints: 3,
    questions: [
      { text: "Numero de deuses no Olimpo", answer: 12 },
      { text: "Numero de trabalhos de Hercules", answer: 12 },
      { text: "Cabecas da Hidra de Lerna", answer: 9 },
      { text: "Olhos dos Ciclopes", answer: 1 },
      { text: "Numero de musas na mitologia grega", answer: 9 },
      { text: "Anos que Odisseu levou para voltar a Itaca", answer: 10 },
    ],
  },
  {
    id: 52, theme: "ENERGIA", patoPoints: 2,
    questions: [
      { text: "Porcentagem de energia renovavel no Brasil", answer: 83 },
      { text: "Numero de usinas nucleares no Brasil", answer: 2 },
      { text: "Porcentagem de energia solar na matriz mundial", answer: 5 },
      { text: "Tempo de vida util de um painel solar (anos)", answer: 25 },
      { text: "Numero de paises que usam 100% energia renovavel", answer: 7 },
      { text: "Velocidade do vento minima para turbina eolica (km/h)", answer: 12 },
    ],
  },
  {
    id: 53, theme: "POKEMON", patoPoints: 2,
    questions: [
      { text: "Numero de tipos elementais de Pokemon", answer: 18 },
      { text: "Numero de geracoes de Pokemon (ate 2025)", answer: 9 },
      { text: "Evolucoes do Eevee", answer: 8 },
      { text: "Numero de insignias para enfrentar a Liga Pokemon", answer: 8 },
      { text: "Preco do card de Charizard mais caro ja vendido (milhares de dolares)", answer: 420 },
      { text: "Numero de episodios do anime Pokemon", answer: 1300 },
    ],
  },
  {
    id: 54, theme: "CHOCOLATE", patoPoints: 2,
    questions: [
      { text: "Porcentagem de cacau no chocolate ao leite", answer: 30 },
      { text: "Toneladas de chocolate consumidas no Brasil por ano (milhares)", answer: 400 },
      { text: "Numero de graos em uma barra de 100g de chocolate", answer: 50 },
      { text: "Preco do chocolate mais caro do mundo por barra (dolares)", answer: 2600 },
      { text: "Porcentagem do mercado de chocolate da Suica no mundo", answer: 18 },
      { text: "Ano de invencao do chocolate em barra", answer: 1847 },
    ],
  },
  {
    id: 55, theme: "TENIS", patoPoints: 2,
    questions: [
      { text: "Numero de titulos de Grand Slam de Novak Djokovic", answer: 24 },
      { text: "Velocidade do saque mais rapido da historia (km/h)", answer: 263 },
      { text: "Duracao da partida mais longa da historia (horas)", answer: 11 },
      { text: "Numero de sets em uma partida de Grand Slam masculina", answer: 3 },
      { text: "Premiacao do campeao de Wimbledon (milhoes de libras)", answer: 2.7 },
      { text: "Idade do campeao mais jovem de Wimbledon", answer: 17 },
    ],
  },
  {
    id: 56, theme: "NEVE & GELO", patoPoints: 3,
    questions: [
      { text: "Porcentagem da superficie da Terra coberta por gelo permanente", answer: 10 },
      { text: "Espessura media do gelo na Antartica (metros)", answer: 2160 },
      { text: "Numero de lados de um floco de neve", answer: 6 },
      { text: "Velocidade maxima de uma avalanche (km/h)", answer: 320 },
      { text: "Temperatura mais fria ja registrada no Brasil (Celsius negativos)", answer: 14 },
      { text: "Numero de palavras para neve no idioma inuit", answer: 50 },
    ],
  },
  {
    id: 57, theme: "FERRAMENTAS", patoPoints: 2,
    questions: [
      { text: "Numero de pecas em um canivete suico basico", answer: 12 },
      { text: "Ano de invencao do martelo pneumatico", answer: 1848 },
      { text: "Numero de dentes em uma serra circular padrao", answer: 24 },
      { text: "Peso de uma marreta de demolicao (kg)", answer: 8 },
      { text: "Numero de funcoes do Leatherman Wave", answer: 18 },
      { text: "Voltagem de uma furadeira domestica nos EUA", answer: 120 },
    ],
  },
  {
    id: 58, theme: "CASTELOS", patoPoints: 3,
    questions: [
      { text: "Numero de castelos na Escocia", answer: 3000 },
      { text: "Numero de torres no Castelo de Windsor", answer: 13 },
      { text: "Anos de construcao da Sagrada Familia (ate sua conclusao)", answer: 144 },
      { text: "Numero de aposentos no Castelo de Versalhes", answer: 2300 },
      { text: "Preco de construcao do Castelo da Cinderela na Disney (milhoes)", answer: 6 },
      { text: "Numero de visitantes ano no Castelo de Edimburgo (milhoes)", answer: 2 },
    ],
  },
  {
    id: 59, theme: "ACIDENTES AEREOS", patoPoints: 3,
    questions: [
      { text: "Porcentagem de accidentes que ocorrem na decolagem ou pouso", answer: 80 },
      { text: "Numero de caixas-pretas em um aviao comercial", answer: 2 },
      { text: "Ano do primeiro voo comercial transatlantico", answer: 1939 },
      { text: "Numero de saidas de emergencia em um Boeing 737", answer: 8 },
      { text: "Tempo medio de investigacao de um acidente aereo (meses)", answer: 18 },
      { text: "Porcentagem de sobreviventes em acidentes aereos fatais", answer: 0 },
    ],
  },
  {
    id: 60, theme: "DESENHOS ANIMADOS", patoPoints: 2,
    questions: [
      { text: "Numero de dedos do Mickey Mouse", answer: 4 },
      { text: "Numero de episodios de Os Simpsons (ate 2025)", answer: 780 },
      { text: "Ano de estreia de Pica-Pau", answer: 1940 },
      { text: "Numero de desenhos animados produzidos por Walt Disney", answer: 81 },
      { text: "Premio do Oscar de Melhor Animacao em 2024 (filme)", answer: 1 },
      { text: "Numero de personagens principais em Scooby-Doo", answer: 5 },
    ],
  },
  {
    id: 61, theme: "SELVA AMAZONICA", patoPoints: 3,
    questions: [
      { text: "Porcentagem da Amazonia que esta no Brasil", answer: 60 },
      { text: "Numero de especies de passaros na Amazonia", answer: 1300 },
      { text: "Comprimento do rio Amazonas (km)", answer: 6992 },
      { text: "Numero de paises que a Amazonia ocupa", answer: 9 },
      { text: "Idade estimada da Floresta Amazonica (milhoes de anos)", answer: 55 },
      { text: "Porcentagem da Amazonia desmatada ate 2025", answer: 17 },
    ],
  },
  {
    id: 62, theme: "CAFE", patoPoints: 2,
    questions: [
      { text: "Porcentagem do cafe mundial produzido pelo Brasil", answer: 33 },
      { text: "Numero de xicaras consumidas por dia no mundo (bilhoes)", answer: 2.5 },
      { text: "Preco do cafe mais caro do mundo por kg (dolares)", answer: 600 },
      { text: "Temperatura ideal da agua para coar cafe (Celsius)", answer: 93 },
      { text: "Numero de estados produtores de cafe no Brasil", answer: 15 },
      { text: "Miligramas de cafeina em uma xicara de espresso", answer: 63 },
    ],
  },
  {
    id: 63, theme: "FOBIA", patoPoints: 2,
    questions: [
      { text: "Porcentagem da populacao com algum tipo de fobia", answer: 10 },
      { text: "Numero de fobias oficialmente catalogadas", answer: 500 },
      { text: "Porcentagem que aracnofobia responde entre as fobias", answer: 30 },
      { text: "Numero de sessoes de terapia para tratar fobia simples", answer: 5 },
      { text: "Porcentagem de pessoas com agorafobia no mundo", answer: 2 },
      { text: "Idade media de inicio das fobias (anos)", answer: 10 },
    ],
  },
  {
    id: 64, theme: "LUZES", patoPoints: 2,
    questions: [
      { text: "Velocidade da luz (km/s)", answer: 300000 },
      { text: "Numero de lumens de uma lampada LED de 10W", answer: 800 },
      { text: "Tempo de vida de uma lampada LED (milhares de horas)", answer: 50 },
      { text: "Porcentagem de energia economizada por LED vs incandescente", answer: 80 },
      { text: "Numero de lampadas na Times Square", answer: 20000 },
      { text: "Ano de invencao da lampada eletrica (Edison)", answer: 1879 },
    ],
  },
  {
    id: 65, theme: "MAGICA", patoPoints: 3,
    questions: [
      { text: "Numero de naipes em um baralho", answer: 4 },
      { text: "Numero de cartas em um baralho padrao", answer: 52 },
      { text: "Numero de truques no livro '13 Steps to Mentalism'", answer: 13 },
      { text: "Preco do pato mecânico de Jacques de Vaucanson no seculo 18 (libras)", answer: 10 },
      { text: "Numero de ilusoes famosas de David Copperfield", answer: 30 },
      { text: "Ano de fundacao do Magic Circle em Londres", answer: 1905 },
    ],
  },
  {
    id: 66, theme: "MERGULHO", patoPoints: 2,
    questions: [
      { text: "Profundidade maxima de mergulho recreativo (metros)", answer: 40 },
      { text: "Recorde mundial de mergulho livre sem assistencia (metros)", answer: 102 },
      { text: "Numero de oceanos no planeta", answer: 5 },
      { text: "Porcentagem de oxigenio em um cilindro de mergulho padrao", answer: 21 },
      { text: "Tempo maximo de mergulho a 10m sem descompressao (minutos)", answer: 219 },
      { text: "Numero de especies de tubaroes inofensivas ao ser humano", answer: 480 },
    ],
  },
  {
    id: 67, theme: "MEMES", patoPoints: 2,
    questions: [
      { text: "Ano de criacao do meme 'Doge'", answer: 2013 },
      { text: "Numero de views do 'Rickroll' original no YouTube (milhoes)", answer: 1500 },
      { text: "Idade do 'Success Kid' na foto original (meses)", answer: 11 },
      { text: "Numero de variacoes do meme 'Distracted Boyfriend'", answer: 5000 },
      { text: "Ano do primeiro meme da internet (Dancing Baby)", answer: 1996 },
      { text: "Numero de personagens no meme 'This is Fine'", answer: 1 },
    ],
  },
  {
    id: 68, theme: "NATAL", patoPoints: 2,
    questions: [
      { text: "Numero de renas do Papai Noel", answer: 9 },
      { text: "Altura da maior arvore de Natal ja construida (metros)", answer: 85 },
      { text: "Numero de presentes nos 12 Dias de Natal", answer: 364 },
      { text: "Porcentagem de pessoas que deixam biscoitos para o Papai Noel", answer: 80 },
      { text: "Preco da casa de 'Esqueceram de Mim' (milhoes de dolares)", answer: 2.4 },
      { text: "Numero de copias vendidas de 'All I Want for Christmas' (milhoes)", answer: 16 },
    ],
  },
  {
    id: 69, theme: "FUTEBOL AMERICANO", patoPoints: 3,
    questions: [
      { text: "Numero de jogadores em campo por time", answer: 11 },
      { text: "Numero de titulos do Super Bowl do Tom Brady", answer: 7 },
      { text: "Jardas para um first down", answer: 10 },
      { text: "Preco do ingresso medio do Super Bowl (milhares de dolares)", answer: 8 },
      { text: "Numero de times na NFL", answer: 32 },
      { text: "Audiencia do Super Bowl nos EUA (milhoes)", answer: 123 },
    ],
  },
  {
    id: 70, theme: "ASTEROIDES", patoPoints: 3,
    questions: [
      { text: "Numero de asteroides no cinturao principal (milhoes)", answer: 1.9 },
      { text: "Diametro do asteroide que extinguiu os dinossauros (km)", answer: 10 },
      { text: "Numero de asteroides que passam perto da Terra por ano (near miss)", answer: 100 },
      { text: "Porcentagem de asteroides que sao do tipo carbonaceo", answer: 75 },
      { text: "Ano da missao DART da NASA", answer: 2022 },
      { text: "Distancia minima considerada 'perigosa' para passagem de asteroide (km)", answer: 7480000 },
    ],
  },
  {
    id: 71, theme: "TATUAGENS", patoPoints: 2,
    questions: [
      { text: "Porcentagem da populacao mundial com tatuagem", answer: 20 },
      { text: "Numero de agulhas em uma maquina de tatuagem", answer: 5 },
      { text: "Preco medio de uma tatuagem pequena nos EUA (dolares)", answer: 100 },
      { text: "Profundidade da agulha na pele durante tatuagem (mm)", answer: 1.5 },
      { text: "Numero de estudios de tatuagem no Brasil", answer: 20000 },
      { text: "Ano da tatuagem mais antiga ja encontrada (a.C.)", answer: 3250 },
    ],
  },
  {
    id: 72, theme: "BALEIAS", patoPoints: 3,
    questions: [
      { text: "Peso de uma baleia azul adulta (toneladas)", answer: 200 },
      { text: "Comprimento da lingua de uma baleia azul (metros)", answer: 3 },
      { text: "Numero de batimentos cardiacos por minuto de uma baleia em repouso", answer: 8 },
      { text: "Profundidade maxima de mergulho de um cachalote (metros)", answer: 3000 },
      { text: "Litros de leite que um filhote de baleia bebe por dia", answer: 380 },
      { text: "Numero de especies de baleias conhecidas", answer: 90 },
    ],
  },
  {
    id: 73, theme: "FORMULA 1", patoPoints: 2,
    questions: [
      { text: "Numero de titulos mundiais de Lewis Hamilton", answer: 7 },
      { text: "Velocidade maxima de um carro de F1 (km/h)", answer: 378 },
      { text: "Numero de equipes na F1 em 2025", answer: 10 },
      { text: "Peso minimo de um carro de F1 (kg)", answer: 798 },
      { text: "Numero de GPs em uma temporada de F1 (2025)", answer: 24 },
      { text: "Preco de um volante de F1 (milhares de dolares)", answer: 50 },
    ],
  },
  {
    id: 74, theme: "IMPÉRIO ROMANO", patoPoints: 3,
    questions: [
      { text: "Numero de imperadores romanos", answer: 70 },
      { text: "Anos de duracao do Imperio Romano", answer: 500 },
      { text: "Numero de legioes no exercito romano", answer: 28 },
      { text: "Comprimento das estradas romanas (km)", answer: 400000 },
      { text: "Populacao de Roma no auge do Imperio (milhoes)", answer: 1 },
      { text: "Numero de assentos no Coliseu (milhares)", answer: 80 },
    ],
  },
  {
    id: 75, theme: "BARBAS", patoPoints: 2,
    questions: [
      { text: "Numero medio de pelos no rosto de um homem adulto", answer: 25000 },
      { text: "Comprimento da barba mais longa ja registrada (metros)", answer: 5.3 },
      { text: "Meses que a barba media leva para crescer 1cm", answer: 1 },
      { text: "Porcentagem de homens que usam barba no mundo", answer: 55 },
      { text: "Numero de campeonatos mundiais de barba realizados", answer: 30 },
      { text: "Preco medio de um corte de barba no Brasil (reais)", answer: 40 },
    ],
  },
  {
    id: 76, theme: "TERREMOTOS", patoPoints: 3,
    questions: [
      { text: "Numero de terremotos detectados por ano no mundo", answer: 500000 },
      { text: "Numero de placas tectonicas principais", answer: 7 },
      { text: "Profundidade media de um terremoto raso (km)", answer: 70 },
      { text: "Magnitude do terremoto de Valdivia 1960", answer: 9.5 },
      { text: "Numero de escalas de magnitude de terremoto usadas", answer: 3 },
      { text: "Ano de invencao do sismografo moderno", answer: 1880 },
    ],
  },
  {
    id: 77, theme: "SUCOS", patoPoints: 2,
    questions: [
      { text: "Numero de laranjas para fazer 1 litro de suco", answer: 12 },
      { text: "Porcentagem do suco de laranja mundial produzido pelo Brasil", answer: 50 },
      { text: "Preco do suco detox mais caro do mundo (dolares)", answer: 36 },
      { text: "Calorias em um copo de 200ml de suco de uva integral", answer: 130 },
      { text: "Numero de sabores de suco da marca Del Valle no Brasil", answer: 20 },
      { text: "Miligramas de vitamina C em 200ml de suco de acerola", answer: 1600 },
    ],
  },
  {
    id: 78, theme: "TRENS", patoPoints: 2,
    questions: [
      { text: "Velocidade maxima do trem-bala japones (km/h)", answer: 320 },
      { text: "Comprimento da ferrovia Transiberiana (km)", answer: 9289 },
      { text: "Numero de estacoes de trem na India", answer: 8000 },
      { text: "Numero de vagoes no trem de carga mais longo ja registrado", answer: 682 },
      { text: "Ano de inauguracao da primeira ferrovia no Brasil", answer: 1854 },
      { text: "Numero de passageiros diarios do metro de Moscou (milhoes)", answer: 7 },
    ],
  },
  {
    id: 79, theme: "BOLHAS DE SABAO", patoPoints: 2,
    questions: [
      { text: "Numero de pessoas dentro da maior bolha de sabao ja feita", answer: 181 },
      { text: "Numero de bolhas estouradas por segundo no recorde mundial", answer: 300 },
      { text: "Comprimento da maior bolha de sabao flutuante (metros)", answer: 40 },
      { text: "Milimetros de espessura da parede de uma bolha de sabao", answer: 0.001 },
      { text: "Numero de ingredientes na receita basica de bolha de sabao", answer: 3 },
      { text: "Ano do primeiro campeonato mundial de bolhas de sabao", answer: 2005 },
    ],
  },
  {
    id: 80, theme: "VIKINGS", patoPoints: 3,
    questions: [
      { text: "Seculo do inicio da Era Viking", answer: 8 },
      { text: "Anos de duracao da Era Viking", answer: 300 },
      { text: "Numero de metros de um navio viking longo (drakkar)", answer: 30 },
      { text: "Numero de remadores em um drakkar tipico", answer: 60 },
      { text: "Porcentagem do ano que os vikings passavam navegando", answer: 50 },
      { text: "Numero de mundos na mitologia nordica", answer: 9 },
    ],
  },
];
