import { Card } from "@/game-engine/types";

export const cards: Card[] = [
  {
    id: 1, theme: "ESPORTES RADICAIS", patoPoints: 2,
    questions: [
      { text: "Altura da maior rampa de skate do mundo (metros)", answer: 30 },
      { text: "Idade do surfista profissional mais velho", answer: 72 },
      { text: "Altura do salto mais alto de skydive (km)", answer: 39 },
      { text: "Recorde humano de apneia - segurar a respiracao debaixo d'agua (minutos)", answer: 24 },
      { text: "Velocidade recorde de um patinador no gelo (km/h)", answer: 103 },
      { text: "Peso maximo de um asa-delta padrao (kg)", answer: 150 },
    ],
  },
  {
    id: 2, theme: "CORPO HUMANO", patoPoints: 3,
    questions: [
      { text: "Comprimento medio do intestino delgado (metros)", answer: 7 },
      { text: "Ossos em uma mao", answer: 27 },
      { text: "Media de pelos em cada narina", answer: 120 },
      { text: "Media de peidos que uma pessoa da por dia", answer: 14 },
      { text: "Peso da pessoa mais pesada de todos os tempos (kg)", answer: 635 },
      { text: "Altura da pessoa mais alta que ja existiu (cm)", answer: 272 },
    ],
  },
  {
    id: 3, theme: "CARROS", patoPoints: 2,
    questions: [
      { text: "Comprimento da limusine mais longa do mundo (metros)", answer: 30 },
      { text: "Recorde de velocidade de um carro de Formula 1 (km/h)", answer: 378 },
      { text: "Numero de estados atravessados pela Rota 66", answer: 8 },
      { text: "Porcentagem de taxis no total de carros no mundo", answer: 1 },
      { text: "Recorde de pessoas dentro de um carro Smart", answer: 20 },
      { text: "Porcentagem de carros que sao pintados de branco", answer: 38 },
    ],
  },
  {
    id: 4, theme: "ARQUITETURA", patoPoints: 3,
    questions: [
      { text: "Numero de andares no Burj Khalifa, o predio mais alto do mundo", answer: 163 },
      { text: "Numero de quartos em Versalhes (em centenas)", answer: 23 },
      { text: "Tamanho medio de um apartamento para alugar em Manhattan (m2)", answer: 65 },
      { text: "Altura do maior castelo de cartas ja construido (cm)", answer: 762 },
      { text: "Numero de degraus ate o topo da catedral de Notre Dame", answer: 387 },
      { text: "Numero de colunas no Partenon em Atenas", answer: 46 },
    ],
  },
  {
    id: 5, theme: "ANIMAIS", patoPoints: 2,
    questions: [
      { text: "Anos de vida de uma tartaruga gigante de Galapagos", answer: 150 },
      { text: "Peso medio de um elefante africano (toneladas)", answer: 6 },
      { text: "Numero de patas de uma centopeia comum", answer: 30 },
      { text: "Velocidade maxima de um guepardo (km/h)", answer: 120 },
      { text: "Altura do salto de uma pulga (cm)", answer: 30 },
      { text: "Numero de especies conhecidas de aranhas", answer: 50000 },
    ],
  },
  {
    id: 6, theme: "ESPACO", patoPoints: 3,
    questions: [
      { text: "Distancia da Terra a Lua (milhares de km)", answer: 384 },
      { text: "Numero de luas de Jupiter", answer: 95 },
      { text: "Temperatura na superficie do Sol (milhares de graus Celsius)", answer: 5500 },
      { text: "Anos que Plutao leva para orbitar o Sol", answer: 248 },
      { text: "Numero de satelites Starlink lancados ate 2025", answer: 7000 },
      { text: "Idade do universo (bilhoes de anos)", answer: 14 },
    ],
  },
  {
    id: 7, theme: "COMIDA", patoPoints: 2,
    questions: [
      { text: "Calorias em um Big Mac", answer: 563 },
      { text: "Numero de pizzas vendidas por dia em Nova York", answer: 230000 },
      { text: "Comprimento do maior sanduiche ja feito (metros)", answer: 735 },
      { text: "Numero de variedades de batata no Peru", answer: 4000 },
      { text: "Preco do cafe mais caro do mundo por xicara (dolares)", answer: 75 },
      { text: "Peso da maior pizza do mundo (kg)", answer: 26000 },
    ],
  },
  {
    id: 8, theme: "DINOSSAUROS", patoPoints: 3,
    questions: [
      { text: "Milhoes de anos desde a extincao dos dinossauros", answer: 65 },
      { text: "Comprimento do maior dinossauro ja descoberto (metros)", answer: 40 },
      { text: "Peso estimado de um T-Rex (toneladas)", answer: 8 },
      { text: "Numero de especies de dinossauros ja identificadas", answer: 700 },
      { text: "Velocidade maxima estimada de um Velociraptor (km/h)", answer: 64 },
      { text: "Comprimento dos dentes do T-Rex (cm)", answer: 30 },
    ],
  },
  {
    id: 9, theme: "BRASIL", patoPoints: 2,
    questions: [
      { text: "Populacao do Brasil em milhoes (2025)", answer: 216 },
      { text: "Numero de estados brasileiros", answer: 26 },
      { text: "Comprimento do rio Amazonas (km)", answer: 6992 },
      { text: "Numero de titulos mundiais de futebol do Brasil", answer: 5 },
      { text: "Porcentagem da Amazonia em territorio brasileiro", answer: 60 },
      { text: "Numero de idiomas indigenas ainda falados no Brasil", answer: 274 },
    ],
  },
  {
    id: 10, theme: "MUSICA", patoPoints: 3,
    questions: [
      { text: "Numero de teclas em um piano padrao", answer: 88 },
      { text: "Numero de sinfonias compostas por Beethoven", answer: 9 },
      { text: "Duracao da musica mais longa ja gravada (horas)", answer: 639 },
      { text: "Numero de streams de 'Blinding Lights' (bilhoes)", answer: 4 },
      { text: "Ano do primeiro festival Woodstock", answer: 1969 },
      { text: "Numero de discos vendidos pelos Beatles (milhoes)", answer: 600 },
    ],
  },
  {
    id: 11, theme: "OCEANOS", patoPoints: 2,
    questions: [
      { text: "Profundidade da Fossa das Marianas (km)", answer: 11 },
      { text: "Porcentagem da superficie da Terra coberta por oceanos", answer: 71 },
      { text: "Numero de especies de tubaroes conhecidas", answer: 500 },
      { text: "Velocidade de natacao de um atum (km/h)", answer: 75 },
      { text: "Numero de coracoes de um polvo", answer: 3 },
      { text: "Peso maximo de uma baleia azul (toneladas)", answer: 200 },
    ],
  },
  {
    id: 12, theme: "CINEMA", patoPoints: 2,
    questions: [
      { text: "Numero de filmes do MCU (ate 2025)", answer: 35 },
      { text: "Duracao do filme mais longo ja feito (horas)", answer: 87 },
      { text: "Orcamento de Avatar (2009) em milhoes de dolares", answer: 237 },
      { text: "Numero de Oscars ganhos por Walt Disney", answer: 26 },
      { text: "Preco do primeiro ingresso de cinema (centavos de dolar)", answer: 5 },
      { text: "Numero de tomadas para a cena da escada em O Poderoso Chefao", answer: 40 },
    ],
  },
  {
    id: 13, theme: "EGITO ANTIGO", patoPoints: 3,
    questions: [
      { text: "Idade estimada das piramides de Gize (milhares de anos)", answer: 4500 },
      { text: "Numero de blocos na Grande Piramide (milhoes)", answer: 2 },
      { text: "Peso medio de cada bloco da Grande Piramide (toneladas)", answer: 2.5 },
      { text: "Numero de dinastias do Egito Antigo", answer: 31 },
      { text: "Comprimento do rio Nilo (km)", answer: 6650 },
      { text: "Numero de deuses no panteao egipcio", answer: 2000 },
    ],
  },
  {
    id: 14, theme: "INTERNET", patoPoints: 2,
    questions: [
      { text: "Numero de sites na internet (bilhoes, 2025)", answer: 2 },
      { text: "Usuarios ativos do Facebook (bilhoes)", answer: 3 },
      { text: "Numero de emails enviados por dia (bilhoes)", answer: 347 },
      { text: "Tempo medio gasto por dia no celular (minutos)", answer: 235 },
      { text: "Porcentagem do trafego da internet que e de bots", answer: 42 },
      { text: "Ano de criacao do primeiro website", answer: 1991 },
    ],
  },
  {
    id: 15, theme: "OLIMPIADAS", patoPoints: 3,
    questions: [
      { text: "Numero de paises participantes em Toquio 2020", answer: 206 },
      { text: "Recorde dos 100m rasos (segundos)", answer: 10 },
      { text: "Numero de medalhas de ouro de Michael Phelps", answer: 23 },
      { text: "Numero de esportes em Paris 2024", answer: 32 },
      { text: "Altura do salto com vara recorde (metros)", answer: 6 },
      { text: "Peso maximo levantado no halterofilismo olimpico (kg)", answer: 264 },
    ],
  },
  {
    id: 16, theme: "FUTEBOL", patoPoints: 2,
    questions: [
      { text: "Numero de gols de Pele na carreira", answer: 1283 },
      { text: "Capacidade do Maracana antes da reforma (milhares)", answer: 200 },
      { text: "Numero de Copas do Mundo disputadas ate 2022", answer: 22 },
      { text: "Recorde de gols em uma unica Copa (por um jogador)", answer: 13 },
      { text: "Numero de paises membros da FIFA", answer: 211 },
      { text: "Distancia percorrida por um jogador em media por jogo (km)", answer: 10 },
    ],
  },
  {
    id: 17, theme: "VOLTA AO MUNDO", patoPoints: 2,
    questions: [
      { text: "Dias que Phileas Fogg levou na historia de Julio Verne", answer: 80 },
      { text: "Numero de fusos horarios no mundo", answer: 24 },
      { text: "Maior temperatura ja registrada na Terra (Celsius)", answer: 57 },
      { text: "Menor temperatura ja registrada na Terra (Celsius negativos)", answer: 89 },
      { text: "Numero de paises no mundo (2025)", answer: 195 },
      { text: "Circunferencia da Terra no Equador (km)", answer: 40075 },
    ],
  },
  {
    id: 18, theme: "TECNOLOGIA", patoPoints: 3,
    questions: [
      { text: "Numero de transistores em um chip M2 Ultra (bilhoes)", answer: 134 },
      { text: "Ano de criacao do primeiro iPhone", answer: 2007 },
      { text: "Peso do primeiro computador ENIAC (toneladas)", answer: 27 },
      { text: "Numero de bits no primeiro processador Intel (4004)", answer: 4 },
      { text: "Velocidade da internet mais rapida ja registrada (Tbps)", answer: 319 },
      { text: "Porcentagem de usuarios mobile vs desktop no mundo", answer: 58 },
    ],
  },
  {
    id: 19, theme: "MEDICINA", patoPoints: 2,
    questions: [
      { text: "Numero de ossos no corpo humano adulto", answer: 206 },
      { text: "Litros de sangue no corpo humano", answer: 5 },
      { text: "Batimentos cardiacos medios por minuto em repouso", answer: 70 },
      { text: "Numero de neuronios no cerebro (bilhoes)", answer: 86 },
      { text: "Temperatura corporal normal (Celsius)", answer: 37 },
      { text: "Porcentagem de agua no corpo humano", answer: 60 },
    ],
  },
  {
    id: 20, theme: "PETS", patoPoints: 2,
    questions: [
      { text: "Numero de caes no Brasil (milhoes, 2025)", answer: 62 },
      { text: "Numero de racas de gatos reconhecidas", answer: 73 },
      { text: "Idade maxima registrada de um cao (anos)", answer: 31 },
      { text: "Numero de dentes de um cao adulto", answer: 42 },
      { text: "Peso do maior cao do mundo (kg)", answer: 155 },
      { text: "Altura do menor cao do mundo (cm)", answer: 10 },
    ],
  },
  {
    id: 21, theme: "DINHEIRO", patoPoints: 3,
    questions: [
      { text: "Fortuna de Jeff Bezos em 2025 (bilhoes de dolares)", answer: 200 },
      { text: "Numero de notas de dolar em circulacao no mundo (bilhoes)", answer: 54 },
      { text: "Ano de criacao do Bitcoin", answer: 2009 },
      { text: "Preco do item mais caro ja vendido no eBay (milhoes)", answer: 4.9 },
      { text: "Numero de centavos na moeda de maior valor facial ja cunhada", answer: 100000000 },
      { text: "Salario minimo mensal no Brasil em 2025 (reais)", answer: 1518 },
    ],
  },
  {
    id: 22, theme: "GUERRAS", patoPoints: 3,
    questions: [
      { text: "Dias que durou a Segunda Guerra Mundial", answer: 2194 },
      { text: "Numero estimado de mortos na Primeira Guerra (milhoes)", answer: 20 },
      { text: "Numero de paises envolvidos na Segunda Guerra", answer: 61 },
      { text: "Anos que durou a Guerra dos Cem Anos", answer: 116 },
      { text: "Numero de bombas atomicas ja detonadas (testes + uso)", answer: 2056 },
      { text: "Tamanho do exercito de Terracota (estatuas)", answer: 8000 },
    ],
  },
  {
    id: 23, theme: "AVIACAO", patoPoints: 2,
    questions: [
      { text: "Velocidade de cruzeiro de um Boeing 747 (km/h)", answer: 920 },
      { text: "Numero de voos comerciais por dia no mundo", answer: 100000 },
      { text: "Altura de voo de um aviao comercial padrao (pes)", answer: 35000 },
      { text: "Comprimento da maior pista de pouso do mundo (km)", answer: 5.5 },
      { text: "Numero de passageiros maximo do Airbus A380", answer: 853 },
      { text: "Ano do primeiro voo dos irmaos Wright", answer: 1903 },
    ],
  },
  {
    id: 24, theme: "MONTANHAS", patoPoints: 2,
    questions: [
      { text: "Altura do Monte Everest (metros)", answer: 8849 },
      { text: "Numero de pessoas que escalaram o Everest (ate 2025)", answer: 12000 },
      { text: "Numero de montanhas com mais de 8000m", answer: 14 },
      { text: "Idade estimada do Monte Everest (milhoes de anos)", answer: 60 },
      { text: "Temperatura minima no topo do Everest (Celsius negativos)", answer: 60 },
      { text: "Numero de mortes no Everest desde 1922", answer: 330 },
    ],
  },
  {
    id: 25, theme: "LITERATURA", patoPoints: 3,
    questions: [
      { text: "Numero de palavras em Dom Quixote (milhares)", answer: 380 },
      { text: "Numero de livros da Biblia", answer: 66 },
      { text: "Idiomas em que Harry Potter foi traduzido", answer: 80 },
      { text: "Numero de pecas escritas por Shakespeare", answer: 39 },
      { text: "Preco do manuscrito mais caro ja vendido (milhoes de dolares)", answer: 30 },
      { text: "Milhoes de copias vendidas de 'O Pequeno Principe'", answer: 200 },
    ],
  },
  {
    id: 26, theme: "VIDEO GAMES", patoPoints: 2,
    questions: [
      { text: "Numero de copias vendidas de Minecraft (milhoes)", answer: 300 },
      { text: "Numero de jogadores ativos de Fortnite (milhoes)", answer: 650 },
      { text: "Ano de lancamento do primeiro PlayStation", answer: 1994 },
      { text: "Bits do Super Nintendo", answer: 16 },
      { text: "Recorde de velocidade no Super Mario 64 (minutos)", answer: 6 },
      { text: "Numero de Pokemon na Pokedex nacional (ate 2025)", answer: 1025 },
    ],
  },
  {
    id: 27, theme: "INSETOS", patoPoints: 2,
    questions: [
      { text: "Numero de especies de formigas conhecidas", answer: 12000 },
      { text: "Numero de olhos de uma abelha", answer: 5 },
      { text: "Velocidade de voo de uma libelula (km/h)", answer: 60 },
      { text: "Peso que uma formiga pode carregar (vezes o proprio peso)", answer: 50 },
      { text: "Numero de pernas de uma lacraia gigante", answer: 42 },
      { text: "Milhoes de anos que as baratas existem", answer: 300 },
    ],
  },
  {
    id: 28, theme: "BEBIDAS", patoPoints: 2,
    questions: [
      { text: "Xicaras de cafe consumidas por dia no mundo (bilhoes)", answer: 2.5 },
      { text: "Numero de garrafas de Coca-Cola vendidas por dia (milhoes)", answer: 2000 },
      { text: "Porcentagem de agua em uma cerveja", answer: 90 },
      { text: "Numero de variedades de uva para vinho", answer: 10000 },
      { text: "Preco do drinque mais caro do mundo (milhares de dolares)", answer: 15 },
      { text: "Idade minima para beber na maioria dos paises da Europa", answer: 18 },
    ],
  },
  {
    id: 29, theme: "RECORDES MUNDIAIS", patoPoints: 3,
    questions: [
      { text: "Numero de malabares simultaneos (recorde mundial)", answer: 14 },
      { text: "Unhas mais longas do mundo acumuladas (metros)", answer: 13 },
      { text: "Maior numero de filhos de uma mulher (recordado)", answer: 69 },
      { text: "Tempo sem dormir recorde (horas)", answer: 264 },
      { text: "Numero de pessoas no maior abraco coletivo", answer: 10000 },
      { text: "Distancia do maior arremesso de anao ja registrado (metros)", answer: 4 },
    ],
  },
  {
    id: 30, theme: "RELIGIAO", patoPoints: 2,
    questions: [
      { text: "Porcentagem de cristaos no mundo", answer: 31 },
      { text: "Porcentagem de muculmanos no mundo", answer: 25 },
      { text: "Numero de papas na historia da Igreja Catolica", answer: 266 },
      { text: "Numero de idiomas em que a Biblia foi traduzida", answer: 700 },
      { text: "Porcentagem de hindus no mundo", answer: 15 },
      { text: "Numero de deuses no hinduismo (aproximado)", answer: 330000000 },
    ],
  },
  {
    id: 31, theme: "PLANETA TERRA", patoPoints: 3,
    questions: [
      { text: "Idade da Terra (bilhoes de anos)", answer: 4.5 },
      { text: "Porcentagem de agua doce na Terra", answer: 3 },
      { text: "Raio da Terra (km)", answer: 6371 },
      { text: "Numero de vulcoes ativos no mundo", answer: 1500 },
      { text: "Velocidade de rotacao da Terra no Equador (km/h)", answer: 1670 },
      { text: "Porcentagem de especies ja extintas", answer: 99 },
    ],
  },
  {
    id: 32, theme: "CELULARES", patoPoints: 2,
    questions: [
      { text: "Numero de smartphones no mundo (bilhoes, 2025)", answer: 7 },
      { text: "Preco do primeiro iPhone nos EUA (dolares)", answer: 499 },
      { text: "Peso do primeiro celular Motorola DynaTAC (kg)", answer: 1.1 },
      { text: "Megapixels da camera do primeiro iPhone", answer: 2 },
      { text: "Numero de chips em um iPhone 15 Pro (bilhoes de transistores)", answer: 19 },
      { text: "Tempo medio de tela diario de um adolescente (horas)", answer: 7 },
    ],
  },
  {
    id: 33, theme: "CIENCIA", patoPoints: 3,
    questions: [
      { text: "Numero de elementos na tabela periodica", answer: 118 },
      { text: "Velocidade da luz (km/s)", answer: 300000 },
      { text: "Numero de atomos no universo observavel (potencia de 10)", answer: 80 },
      { text: "Temperatura do zero absoluto (Celsius negativos)", answer: 273 },
      { text: "Numero de Premios Nobel em ciencias entregues ate 2025", answer: 653 },
      { text: "Anos desde a publicacao de 'Origem das Especies' de Darwin", answer: 166 },
    ],
  },
  {
    id: 34, theme: "MODA", patoPoints: 2,
    questions: [
      { text: "Tamanho do salto mais alto ja feito (cm)", answer: 30 },
      { text: "Numero de pares de tenis vendidos por ano no mundo (bilhoes)", answer: 23 },
      { text: "Preco do vestido mais caro ja feito (milhoes de dolares)", answer: 30 },
      { text: "Numero de desfiles na Semana de Moda de Paris", answer: 90 },
      { text: "Ano de fundacao da Louis Vuitton", answer: 1854 },
      { text: "Porcentagem do mercado de luxo controlado pela LVMH", answer: 25 },
    ],
  },
  {
    id: 35, theme: "CURIOSIDADES", patoPoints: 2,
    questions: [
      { text: "Numero de linguas de sogra vendidas por ano no Brasil (milhoes)", answer: 25 },
      { text: "Velocidade de um espirro (km/h)", answer: 160 },
      { text: "Porcentagem de canhotos no mundo", answer: 10 },
      { text: "Numero de vezes que piscamos por dia (milhares)", answer: 28 },
      { text: "Comprimento total de vasos sanguineos no corpo humano (km)", answer: 100000 },
      { text: "Numero de saborizantes em um Doritos Nacho Cheese", answer: 30 },
    ],
  },
  {
    id: 36, theme: "CONSTRUCAO", patoPoints: 2,
    questions: [
      { text: "Andares do maior arranha-ceu do Brasil (One Tower)", answer: 84 },
      { text: "Numero de tuneis na Muralha da China", answer: 0 },
      { text: "Comprimento da Grande Muralha da China (km)", answer: 21196 },
      { text: "Numero de operarios que construiram Brasilia", answer: 60000 },
      { text: "Anos para construir a Sagrada Familia (ate hoje)", answer: 143 },
      { text: "Numero de pontes em Veneza", answer: 391 },
    ],
  },
  {
    id: 37, theme: "CATASTROFES", patoPoints: 3,
    questions: [
      { text: "Magnitude do terremoto mais forte ja registrado", answer: 9.5 },
      { text: "Numero de mortos na Peste Negra (milhoes, Europa)", answer: 50 },
      { text: "Ano da erupcao do Vesuvio que destruiu Pompeia", answer: 79 },
      { text: "Altura do maior tsunami registrado (metros)", answer: 524 },
      { text: "Numero de mortos no Titanic", answer: 1514 },
      { text: "Diametro do meteoro que extinguiu os dinossauros (km)", answer: 10 },
    ],
  },
  {
    id: 38, theme: "REDES SOCIAIS", patoPoints: 2,
    questions: [
      { text: "Usuarios mensais do Instagram (bilhoes)", answer: 2 },
      { text: "Numero maximo de caracteres em um tweet (em 2025)", answer: 280 },
      { text: "Ano de fundacao do TikTok", answer: 2016 },
      { text: "Videos enviados por minuto no YouTube (horas)", answer: 500 },
      { text: "Usuarios do LinkedIn (milhoes)", answer: 1000 },
      { text: "Numero de funcionarios do Facebook/Meta (milhares)", answer: 70 },
    ],
  },
  {
    id: 39, theme: "PIRATAS", patoPoints: 3,
    questions: [
      { text: "Seculo da Era de Ouro da Pirataria", answer: 18 },
      { text: "Numero de canhoes no Queen Anne's Revenge (Barba Negra)", answer: 40 },
      { text: "Numero de esposas de Barba Negra", answer: 14 },
      { text: "Anos que durou a Era de Ouro da Pirataria", answer: 100 },
      { text: "Numero de capitulos do Codigo dos Piratas", answer: 9 },
      { text: "Porcentagem de piratas que morriam de doenca (nao em batalha)", answer: 50 },
    ],
  },
  {
    id: 40, theme: "SAMBA & CARNAVAL", patoPoints: 2,
    questions: [
      { text: "Numero de escolas de samba no Grupo Especial do Rio", answer: 12 },
      { text: "Minutos de desfile de cada escola de samba no RJ", answer: 75 },
      { text: "Numero de componentes em uma escola de samba (media)", answer: 3500 },
      { text: "Turistas no carnaval do Rio por ano (milhoes)", answer: 2 },
      { text: "Preco da fantasia mais cara da Sapucai (milhares de reais)", answer: 50 },
      { text: "Ano do primeiro desfile oficial de carnaval no Rio", answer: 1932 },
    ],
  },
  {
    id: 41, theme: "COPA DO MUNDO", patoPoints: 3,
    questions: [
      { text: "Numero de gols na carreira de Copa de Miroslav Klose", answer: 16 },
      { text: "Numero de paises-sede diferentes ate 2022", answer: 17 },
      { text: "Capacidade do maior estadio de Copa (Maracana em 1950)", answer: 200000 },
      { text: "Numero de jogos em uma Copa de 32 times", answer: 64 },
      { text: "Premiacao do campeao da Copa 2022 (milhoes de dolares)", answer: 42 },
      { text: "Numero de cartoes amarelos na Copa 2022", answer: 227 },
    ],
  },
  {
    id: 42, theme: "ARTES", patoPoints: 2,
    questions: [
      { text: "Preco da pintura mais cara ja vendida (milhoes de dolares)", answer: 450 },
      { text: "Numero de obras de Van Gogh", answer: 900 },
      { text: "Anos que Leonardo da Vinci pintou a Mona Lisa", answer: 4 },
      { text: "Peso da estatua do Cristo Redentor (toneladas)", answer: 1145 },
      { text: "Altura da estatua do Cristo Redentor (metros)", answer: 38 },
      { text: "Numero de museus no Louvre", answer: 1 },
    ],
  },
  {
    id: 43, theme: "PLANTAS", patoPoints: 2,
    questions: [
      { text: "Numero de especies de arvores na Amazonia", answer: 16000 },
      { text: "Idade da arvore mais velha do mundo (anos)", answer: 5000 },
      { text: "Altura da maior arvore do mundo (metros)", answer: 116 },
      { text: "Numero de flores que uma abelha visita por dia", answer: 5000 },
      { text: "Peso da maior abobora ja cultivada (kg)", answer: 1247 },
      { text: "Porcentagem de oxigenio produzido por algas marinhas", answer: 50 },
    ],
  },
  {
    id: 44, theme: "PSICOLOGIA", patoPoints: 3,
    questions: [
      { text: "Numero medio de sonhos por noite", answer: 5 },
      { text: "Porcentagem de sonhos que esquecidos em 5 minutos", answer: 50 },
      { text: "Horas de sono recomendadas para adultos", answer: 8 },
      { text: "Numero de fobias catalogadas", answer: 500 },
      { text: "Porcentagem da populacao com aracnofobia", answer: 5 },
      { text: "QI medio da populacao mundial", answer: 100 },
    ],
  },
  {
    id: 45, theme: "SHOPPING", patoPoints: 2,
    questions: [
      { text: "Numero de lojas no maior shopping do Brasil", answer: 600 },
      { text: "Porcentagem de compras feitas online no Brasil (2025)", answer: 15 },
      { text: "Numero de shoppings centers no Brasil", answer: 620 },
      { text: "Faturamento na Black Friday Brasil 2024 (bilhoes de reais)", answer: 8 },
      { text: "Tamanho do maior shopping do mundo (milhares de m2)", answer: 660 },
      { text: "Ano de abertura do primeiro shopping do Brasil", answer: 1966 },
    ],
  },
  {
    id: 46, theme: "FESTAS JUNINAS", patoPoints: 2,
    questions: [
      { text: "Numero de dias de festa junina em Campina Grande", answer: 30 },
      { text: "Altura da maior fogueira junina ja construida (metros)", answer: 40 },
      { text: "Numero de comidas tipicas listadas oficialmente", answer: 30 },
      { text: "Publico da maior festa junina do Brasil (milhoes)", answer: 2.5 },
      { text: "Numero de quadrilhas na final nacional de quadrilha junina", answer: 20 },
      { text: "Toneladas de milho consumidas nas festas juninas do Nordeste", answer: 3000 },
    ],
  },
  {
    id: 47, theme: "MISTERIOS", patoPoints: 3,
    questions: [
      { text: "Numero de pedras em Stonehenge", answer: 83 },
      { text: "Anos que o Triangulo das Bermudas e considerado misterio", answer: 80 },
      { text: "Profundidade do Lago Ness (metros)", answer: 230 },
      { text: "Numero de linhas de Nazca descobertas", answer: 300 },
      { text: "Peso das estatuas da Ilha de Pascoa (toneladas)", answer: 14 },
      { text: "Numero de sitios arqueologicos maias conhecidos", answer: 4400 },
    ],
  },
  {
    id: 48, theme: "FAMOSOS", patoPoints: 2,
    questions: [
      { text: "Seguidores de Cristiano Ronaldo no Instagram (milhoes)", answer: 650 },
      { text: "Numero de Grammys ganhos por Beyonce", answer: 32 },
      { text: "Idade de Morgan Freeman ao ganhar seu primeiro Oscar", answer: 67 },
      { text: "Numero de filmes com participacao de Stan Lee (cameo)", answer: 50 },
      { text: "Fortuna de Taylor Swift em 2025 (bilhoes de dolares)", answer: 1.6 },
      { text: "Numero de musicas gravadas por Roberto Carlos", answer: 600 },
    ],
  },
  {
    id: 49, theme: "TRANSPORTE PUBLICO", patoPoints: 2,
    questions: [
      { text: "Numero de estacoes do metro de Sao Paulo", answer: 91 },
      { text: "Passageiros diarios do metro de Toquio (milhoes)", answer: 9 },
      { text: "Numero de cidades com metro no Brasil", answer: 7 },
      { text: "Velocidade maxima do trem-bala japones (km/h)", answer: 320 },
      { text: "Extensao total de ciclovias em Copenhagen (km)", answer: 500 },
      { text: "Numero de onibus em circulacao no Brasil (milhares)", answer: 400 },
    ],
  },
  {
    id: 50, theme: "DATAS & CALENDARIO", patoPoints: 3,
    questions: [
      { text: "Numero de dias em um ano bissexto", answer: 366 },
      { text: "Numero de meses com 31 dias", answer: 7 },
      { text: "Numero de fusos horarios na Russia", answer: 11 },
      { text: "Dias de atraso do calendario juliano por seculo", answer: 3 },
      { text: "Numero de anos em uma decada", answer: 10 },
      { text: "Numero de semanas em um ano", answer: 52 },
    ],
  },
];
